<?php

declare(strict_types=1);

/**
 * DangerousGoods
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Toppy\Sendcloud\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
/**
 * Sendcloud Public REST API
 *
 * Complete Sendcloud API v2 specification - merged from official sendcloud.dev documentation
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@sendcloud.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
namespace Toppy\Sendcloud\V2\Model;

use \ArrayAccess;
use \Toppy\Sendcloud\V2\ObjectSerializer;

/**
 * DangerousGoods Class Doc Comment
 *
 * @category Class
 * @description Hazardous materials information for items.
 * @package  Toppy\Sendcloud\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class DangerousGoods implements ModelInterface, ArrayAccess, \JsonSerializable, \Stringable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'dangerous-goods';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'chemicalRecordIdentifier' => 'string',
        'regulationSet' => 'string',
        'packagingTypeQuantity' => 'string',
        'packagingType' => 'string',
        'packagingInstructionCode' => 'string',
        'idNumber' => 'string',
        'classDivisionNumber' => 'string',
        'quantity' => 'string',
        'unitOfMeasurement' => 'string',
        'properShippingName' => 'string',
        'commodityRegulatedLevelCode' => 'string',
        'transportationMode' => 'string',
        'emergencyContactName' => 'string',
        'emergencyContactPhone' => 'string',
        'adrPackingGroupLetter' => 'string',
        'localProperShippingName' => 'string',
        'transportCategory' => 'string',
        'tunnelRestrictionCode' => 'string',
        'weightType' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'chemicalRecordIdentifier' => null,
        'regulationSet' => null,
        'packagingTypeQuantity' => null,
        'packagingType' => null,
        'packagingInstructionCode' => null,
        'idNumber' => null,
        'classDivisionNumber' => null,
        'quantity' => null,
        'unitOfMeasurement' => null,
        'properShippingName' => null,
        'commodityRegulatedLevelCode' => null,
        'transportationMode' => null,
        'emergencyContactName' => null,
        'emergencyContactPhone' => null,
        'adrPackingGroupLetter' => null,
        'localProperShippingName' => null,
        'transportCategory' => null,
        'tunnelRestrictionCode' => null,
        'weightType' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'chemicalRecordIdentifier' => true,
        'regulationSet' => false,
        'packagingTypeQuantity' => true,
        'packagingType' => true,
        'packagingInstructionCode' => true,
        'idNumber' => true,
        'classDivisionNumber' => true,
        'quantity' => true,
        'unitOfMeasurement' => false,
        'properShippingName' => true,
        'commodityRegulatedLevelCode' => false,
        'transportationMode' => false,
        'emergencyContactName' => true,
        'emergencyContactPhone' => true,
        'adrPackingGroupLetter' => false,
        'localProperShippingName' => true,
        'transportCategory' => true,
        'tunnelRestrictionCode' => true,
        'weightType' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->openAPINullablesSetToNull, true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'chemicalRecordIdentifier' => 'chemical_record_identifier',
        'regulationSet' => 'regulation_set',
        'packagingTypeQuantity' => 'packaging_type_quantity',
        'packagingType' => 'packaging_type',
        'packagingInstructionCode' => 'packaging_instruction_code',
        'idNumber' => 'id_number',
        'classDivisionNumber' => 'class_division_number',
        'quantity' => 'quantity',
        'unitOfMeasurement' => 'unit_of_measurement',
        'properShippingName' => 'proper_shipping_name',
        'commodityRegulatedLevelCode' => 'commodity_regulated_level_code',
        'transportationMode' => 'transportation_mode',
        'emergencyContactName' => 'emergency_contact_name',
        'emergencyContactPhone' => 'emergency_contact_phone',
        'adrPackingGroupLetter' => 'adr_packing_group_letter',
        'localProperShippingName' => 'local_proper_shipping_name',
        'transportCategory' => 'transport_category',
        'tunnelRestrictionCode' => 'tunnel_restriction_code',
        'weightType' => 'weight_type'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'chemicalRecordIdentifier' => 'setChemicalRecordIdentifier',
        'regulationSet' => 'setRegulationSet',
        'packagingTypeQuantity' => 'setPackagingTypeQuantity',
        'packagingType' => 'setPackagingType',
        'packagingInstructionCode' => 'setPackagingInstructionCode',
        'idNumber' => 'setIdNumber',
        'classDivisionNumber' => 'setClassDivisionNumber',
        'quantity' => 'setQuantity',
        'unitOfMeasurement' => 'setUnitOfMeasurement',
        'properShippingName' => 'setProperShippingName',
        'commodityRegulatedLevelCode' => 'setCommodityRegulatedLevelCode',
        'transportationMode' => 'setTransportationMode',
        'emergencyContactName' => 'setEmergencyContactName',
        'emergencyContactPhone' => 'setEmergencyContactPhone',
        'adrPackingGroupLetter' => 'setAdrPackingGroupLetter',
        'localProperShippingName' => 'setLocalProperShippingName',
        'transportCategory' => 'setTransportCategory',
        'tunnelRestrictionCode' => 'setTunnelRestrictionCode',
        'weightType' => 'setWeightType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'chemicalRecordIdentifier' => 'getChemicalRecordIdentifier',
        'regulationSet' => 'getRegulationSet',
        'packagingTypeQuantity' => 'getPackagingTypeQuantity',
        'packagingType' => 'getPackagingType',
        'packagingInstructionCode' => 'getPackagingInstructionCode',
        'idNumber' => 'getIdNumber',
        'classDivisionNumber' => 'getClassDivisionNumber',
        'quantity' => 'getQuantity',
        'unitOfMeasurement' => 'getUnitOfMeasurement',
        'properShippingName' => 'getProperShippingName',
        'commodityRegulatedLevelCode' => 'getCommodityRegulatedLevelCode',
        'transportationMode' => 'getTransportationMode',
        'emergencyContactName' => 'getEmergencyContactName',
        'emergencyContactPhone' => 'getEmergencyContactPhone',
        'adrPackingGroupLetter' => 'getAdrPackingGroupLetter',
        'localProperShippingName' => 'getLocalProperShippingName',
        'transportCategory' => 'getTransportCategory',
        'tunnelRestrictionCode' => 'getTunnelRestrictionCode',
        'weightType' => 'getWeightType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const REGULATION_SET_IATA = 'IATA';

    public const REGULATION_SET_ADR = 'ADR';

    public const UNIT_OF_MEASUREMENT_KG = 'KG';

    public const UNIT_OF_MEASUREMENT_G = 'G';

    public const UNIT_OF_MEASUREMENT_L = 'L';

    public const UNIT_OF_MEASUREMENT_ML = 'ML';

    public const COMMODITY_REGULATED_LEVEL_CODE_LQ = 'LQ';

    public const COMMODITY_REGULATED_LEVEL_CODE_EQ = 'EQ';

    public const TRANSPORTATION_MODE_HIGHWAY = 'Highway';

    public const TRANSPORTATION_MODE_GROUND = 'Ground';

    public const TRANSPORTATION_MODE_PAX = 'PAX';

    public const TRANSPORTATION_MODE_CAO = 'CAO';

    public const ADR_PACKING_GROUP_LETTER_I = 'I';

    public const ADR_PACKING_GROUP_LETTER_II = 'II';

    public const ADR_PACKING_GROUP_LETTER_III = 'III';

    public const WEIGHT_TYPE_NET = 'Net';

    public const WEIGHT_TYPE_GROSS = 'Gross';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getRegulationSetAllowableValues()
    {
        return [
            self::REGULATION_SET_IATA,
            self::REGULATION_SET_ADR,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getUnitOfMeasurementAllowableValues()
    {
        return [
            self::UNIT_OF_MEASUREMENT_KG,
            self::UNIT_OF_MEASUREMENT_G,
            self::UNIT_OF_MEASUREMENT_L,
            self::UNIT_OF_MEASUREMENT_ML,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCommodityRegulatedLevelCodeAllowableValues()
    {
        return [
            self::COMMODITY_REGULATED_LEVEL_CODE_LQ,
            self::COMMODITY_REGULATED_LEVEL_CODE_EQ,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTransportationModeAllowableValues()
    {
        return [
            self::TRANSPORTATION_MODE_HIGHWAY,
            self::TRANSPORTATION_MODE_GROUND,
            self::TRANSPORTATION_MODE_PAX,
            self::TRANSPORTATION_MODE_CAO,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAdrPackingGroupLetterAllowableValues()
    {
        return [
            self::ADR_PACKING_GROUP_LETTER_I,
            self::ADR_PACKING_GROUP_LETTER_II,
            self::ADR_PACKING_GROUP_LETTER_III,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getWeightTypeAllowableValues()
    {
        return [
            self::WEIGHT_TYPE_NET,
            self::WEIGHT_TYPE_GROSS,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('chemicalRecordIdentifier', $data ?? [], null);
        $this->setIfExists('regulationSet', $data ?? [], null);
        $this->setIfExists('packagingTypeQuantity', $data ?? [], null);
        $this->setIfExists('packagingType', $data ?? [], null);
        $this->setIfExists('packagingInstructionCode', $data ?? [], null);
        $this->setIfExists('idNumber', $data ?? [], null);
        $this->setIfExists('classDivisionNumber', $data ?? [], null);
        $this->setIfExists('quantity', $data ?? [], null);
        $this->setIfExists('unitOfMeasurement', $data ?? [], null);
        $this->setIfExists('properShippingName', $data ?? [], null);
        $this->setIfExists('commodityRegulatedLevelCode', $data ?? [], null);
        $this->setIfExists('transportationMode', $data ?? [], null);
        $this->setIfExists('emergencyContactName', $data ?? [], null);
        $this->setIfExists('emergencyContactPhone', $data ?? [], null);
        $this->setIfExists('adrPackingGroupLetter', $data ?? [], null);
        $this->setIfExists('localProperShippingName', $data ?? [], null);
        $this->setIfExists('transportCategory', $data ?? [], null);
        $this->setIfExists('tunnelRestrictionCode', $data ?? [], null);
        $this->setIfExists('weightType', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param mixed  $defaultValue
     * @param array<string, mixed> $fields
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getRegulationSetAllowableValues();
        if (!is_null($this->container['regulationSet']) && !in_array($this->container['regulationSet'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'regulationSet', must be one of '%s'",
                $this->container['regulationSet'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getUnitOfMeasurementAllowableValues();
        if (!is_null($this->container['unitOfMeasurement']) && !in_array($this->container['unitOfMeasurement'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'unitOfMeasurement', must be one of '%s'",
                $this->container['unitOfMeasurement'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getCommodityRegulatedLevelCodeAllowableValues();
        if (!is_null($this->container['commodityRegulatedLevelCode']) && !in_array($this->container['commodityRegulatedLevelCode'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'commodityRegulatedLevelCode', must be one of '%s'",
                $this->container['commodityRegulatedLevelCode'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getTransportationModeAllowableValues();
        if (!is_null($this->container['transportationMode']) && !in_array($this->container['transportationMode'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'transportationMode', must be one of '%s'",
                $this->container['transportationMode'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getAdrPackingGroupLetterAllowableValues();
        if (!is_null($this->container['adrPackingGroupLetter']) && !in_array($this->container['adrPackingGroupLetter'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'adrPackingGroupLetter', must be one of '%s'",
                $this->container['adrPackingGroupLetter'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getWeightTypeAllowableValues();
        if (!is_null($this->container['weightType']) && !in_array($this->container['weightType'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'weightType', must be one of '%s'",
                $this->container['weightType'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets chemicalRecordIdentifier
     *
     * @return string|null
     */
    public function getChemicalRecordIdentifier()
    {
        return $this->container['chemicalRecordIdentifier'];
    }

    /**
     * Sets chemicalRecordIdentifier
     *
     * @param string|null $chemicalRecordIdentifier Chemical record identifier for the dangerous goods
     *
     * @return self
     */
    public function setChemicalRecordIdentifier($chemicalRecordIdentifier)
    {
        if (is_null($chemicalRecordIdentifier)) {
            $this->openAPINullablesSetToNull[] = 'chemicalRecordIdentifier';
        } else {
            $nullablesSetToNull = $this->openAPINullablesSetToNull;
            $index = array_search('chemicalRecordIdentifier', $nullablesSetToNull, true);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['chemicalRecordIdentifier'] = $chemicalRecordIdentifier;

        return $this;
    }

    /**
     * Gets regulationSet
     *
     * @return string|null
     */
    public function getRegulationSet()
    {
        return $this->container['regulationSet'];
    }

    /**
     * Sets regulationSet
     *
     * @param string|null $regulationSet Regulation set governing the dangerous goods
     *
     * @return self
     */
    public function setRegulationSet($regulationSet)
    {
        if (is_null($regulationSet)) {
            throw new \InvalidArgumentException('non-nullable regulationSet cannot be null');
        }

        $allowedValues = $this->getRegulationSetAllowableValues();
        if (!in_array($regulationSet, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'regulationSet', must be one of '%s'",
                    $regulationSet,
                    implode("', '", $allowedValues)
                )
            );
        }

        $this->container['regulationSet'] = $regulationSet;

        return $this;
    }

    /**
     * Gets packagingTypeQuantity
     *
     * @return string|null
     */
    public function getPackagingTypeQuantity()
    {
        return $this->container['packagingTypeQuantity'];
    }

    /**
     * Sets packagingTypeQuantity
     *
     * @param string|null $packagingTypeQuantity Quantity of packaging type
     *
     * @return self
     */
    public function setPackagingTypeQuantity($packagingTypeQuantity)
    {
        if (is_null($packagingTypeQuantity)) {
            $this->openAPINullablesSetToNull[] = 'packagingTypeQuantity';
        } else {
            $nullablesSetToNull = $this->openAPINullablesSetToNull;
            $index = array_search('packagingTypeQuantity', $nullablesSetToNull, true);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['packagingTypeQuantity'] = $packagingTypeQuantity;

        return $this;
    }

    /**
     * Gets packagingType
     *
     * @return string|null
     */
    public function getPackagingType()
    {
        return $this->container['packagingType'];
    }

    /**
     * Sets packagingType
     *
     * @param string|null $packagingType Type of packaging used
     *
     * @return self
     */
    public function setPackagingType($packagingType)
    {
        if (is_null($packagingType)) {
            $this->openAPINullablesSetToNull[] = 'packagingType';
        } else {
            $nullablesSetToNull = $this->openAPINullablesSetToNull;
            $index = array_search('packagingType', $nullablesSetToNull, true);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['packagingType'] = $packagingType;

        return $this;
    }

    /**
     * Gets packagingInstructionCode
     *
     * @return string|null
     */
    public function getPackagingInstructionCode()
    {
        return $this->container['packagingInstructionCode'];
    }

    /**
     * Sets packagingInstructionCode
     *
     * @param string|null $packagingInstructionCode Packaging instruction code
     *
     * @return self
     */
    public function setPackagingInstructionCode($packagingInstructionCode)
    {
        if (is_null($packagingInstructionCode)) {
            $this->openAPINullablesSetToNull[] = 'packagingInstructionCode';
        } else {
            $nullablesSetToNull = $this->openAPINullablesSetToNull;
            $index = array_search('packagingInstructionCode', $nullablesSetToNull, true);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['packagingInstructionCode'] = $packagingInstructionCode;

        return $this;
    }

    /**
     * Gets idNumber
     *
     * @return string|null
     */
    public function getIdNumber()
    {
        return $this->container['idNumber'];
    }

    /**
     * Sets idNumber
     *
     * @param string|null $idNumber UN identification number
     *
     * @return self
     */
    public function setIdNumber($idNumber)
    {
        if (is_null($idNumber)) {
            $this->openAPINullablesSetToNull[] = 'idNumber';
        } else {
            $nullablesSetToNull = $this->openAPINullablesSetToNull;
            $index = array_search('idNumber', $nullablesSetToNull, true);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['idNumber'] = $idNumber;

        return $this;
    }

    /**
     * Gets classDivisionNumber
     *
     * @return string|null
     */
    public function getClassDivisionNumber()
    {
        return $this->container['classDivisionNumber'];
    }

    /**
     * Sets classDivisionNumber
     *
     * @param string|null $classDivisionNumber Hazard class and division number
     *
     * @return self
     */
    public function setClassDivisionNumber($classDivisionNumber)
    {
        if (is_null($classDivisionNumber)) {
            $this->openAPINullablesSetToNull[] = 'classDivisionNumber';
        } else {
            $nullablesSetToNull = $this->openAPINullablesSetToNull;
            $index = array_search('classDivisionNumber', $nullablesSetToNull, true);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['classDivisionNumber'] = $classDivisionNumber;

        return $this;
    }

    /**
     * Gets quantity
     *
     * @return string|null
     */
    public function getQuantity()
    {
        return $this->container['quantity'];
    }

    /**
     * Sets quantity
     *
     * @param string|null $quantity Quantity of dangerous goods
     *
     * @return self
     */
    public function setQuantity($quantity)
    {
        if (is_null($quantity)) {
            $this->openAPINullablesSetToNull[] = 'quantity';
        } else {
            $nullablesSetToNull = $this->openAPINullablesSetToNull;
            $index = array_search('quantity', $nullablesSetToNull, true);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['quantity'] = $quantity;

        return $this;
    }

    /**
     * Gets unitOfMeasurement
     *
     * @return string|null
     */
    public function getUnitOfMeasurement()
    {
        return $this->container['unitOfMeasurement'];
    }

    /**
     * Sets unitOfMeasurement
     *
     * @param string|null $unitOfMeasurement Unit of measurement for dangerous goods quantity
     *
     * @return self
     */
    public function setUnitOfMeasurement($unitOfMeasurement)
    {
        if (is_null($unitOfMeasurement)) {
            throw new \InvalidArgumentException('non-nullable unitOfMeasurement cannot be null');
        }

        $allowedValues = $this->getUnitOfMeasurementAllowableValues();
        if (!in_array($unitOfMeasurement, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'unitOfMeasurement', must be one of '%s'",
                    $unitOfMeasurement,
                    implode("', '", $allowedValues)
                )
            );
        }

        $this->container['unitOfMeasurement'] = $unitOfMeasurement;

        return $this;
    }

    /**
     * Gets properShippingName
     *
     * @return string|null
     */
    public function getProperShippingName()
    {
        return $this->container['properShippingName'];
    }

    /**
     * Sets properShippingName
     *
     * @param string|null $properShippingName Proper shipping name as defined by regulations
     *
     * @return self
     */
    public function setProperShippingName($properShippingName)
    {
        if (is_null($properShippingName)) {
            $this->openAPINullablesSetToNull[] = 'properShippingName';
        } else {
            $nullablesSetToNull = $this->openAPINullablesSetToNull;
            $index = array_search('properShippingName', $nullablesSetToNull, true);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['properShippingName'] = $properShippingName;

        return $this;
    }

    /**
     * Gets commodityRegulatedLevelCode
     *
     * @return string|null
     */
    public function getCommodityRegulatedLevelCode()
    {
        return $this->container['commodityRegulatedLevelCode'];
    }

    /**
     * Sets commodityRegulatedLevelCode
     *
     * @param string|null $commodityRegulatedLevelCode Commodity regulated level code
     *
     * @return self
     */
    public function setCommodityRegulatedLevelCode($commodityRegulatedLevelCode)
    {
        if (is_null($commodityRegulatedLevelCode)) {
            throw new \InvalidArgumentException('non-nullable commodityRegulatedLevelCode cannot be null');
        }

        $allowedValues = $this->getCommodityRegulatedLevelCodeAllowableValues();
        if (!in_array($commodityRegulatedLevelCode, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'commodityRegulatedLevelCode', must be one of '%s'",
                    $commodityRegulatedLevelCode,
                    implode("', '", $allowedValues)
                )
            );
        }

        $this->container['commodityRegulatedLevelCode'] = $commodityRegulatedLevelCode;

        return $this;
    }

    /**
     * Gets transportationMode
     *
     * @return string|null
     */
    public function getTransportationMode()
    {
        return $this->container['transportationMode'];
    }

    /**
     * Sets transportationMode
     *
     * @param string|null $transportationMode Mode of transportation
     *
     * @return self
     */
    public function setTransportationMode($transportationMode)
    {
        if (is_null($transportationMode)) {
            throw new \InvalidArgumentException('non-nullable transportationMode cannot be null');
        }

        $allowedValues = $this->getTransportationModeAllowableValues();
        if (!in_array($transportationMode, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'transportationMode', must be one of '%s'",
                    $transportationMode,
                    implode("', '", $allowedValues)
                )
            );
        }

        $this->container['transportationMode'] = $transportationMode;

        return $this;
    }

    /**
     * Gets emergencyContactName
     *
     * @return string|null
     */
    public function getEmergencyContactName()
    {
        return $this->container['emergencyContactName'];
    }

    /**
     * Sets emergencyContactName
     *
     * @param string|null $emergencyContactName Name of emergency contact person
     *
     * @return self
     */
    public function setEmergencyContactName($emergencyContactName)
    {
        if (is_null($emergencyContactName)) {
            $this->openAPINullablesSetToNull[] = 'emergencyContactName';
        } else {
            $nullablesSetToNull = $this->openAPINullablesSetToNull;
            $index = array_search('emergencyContactName', $nullablesSetToNull, true);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['emergencyContactName'] = $emergencyContactName;

        return $this;
    }

    /**
     * Gets emergencyContactPhone
     *
     * @return string|null
     */
    public function getEmergencyContactPhone()
    {
        return $this->container['emergencyContactPhone'];
    }

    /**
     * Sets emergencyContactPhone
     *
     * @param string|null $emergencyContactPhone Phone number of emergency contact
     *
     * @return self
     */
    public function setEmergencyContactPhone($emergencyContactPhone)
    {
        if (is_null($emergencyContactPhone)) {
            $this->openAPINullablesSetToNull[] = 'emergencyContactPhone';
        } else {
            $nullablesSetToNull = $this->openAPINullablesSetToNull;
            $index = array_search('emergencyContactPhone', $nullablesSetToNull, true);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['emergencyContactPhone'] = $emergencyContactPhone;

        return $this;
    }

    /**
     * Gets adrPackingGroupLetter
     *
     * @return string|null
     */
    public function getAdrPackingGroupLetter()
    {
        return $this->container['adrPackingGroupLetter'];
    }

    /**
     * Sets adrPackingGroupLetter
     *
     * @param string|null $adrPackingGroupLetter ADR packing group classification
     *
     * @return self
     */
    public function setAdrPackingGroupLetter($adrPackingGroupLetter)
    {
        if (is_null($adrPackingGroupLetter)) {
            throw new \InvalidArgumentException('non-nullable adrPackingGroupLetter cannot be null');
        }

        $allowedValues = $this->getAdrPackingGroupLetterAllowableValues();
        if (!in_array($adrPackingGroupLetter, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'adrPackingGroupLetter', must be one of '%s'",
                    $adrPackingGroupLetter,
                    implode("', '", $allowedValues)
                )
            );
        }

        $this->container['adrPackingGroupLetter'] = $adrPackingGroupLetter;

        return $this;
    }

    /**
     * Gets localProperShippingName
     *
     * @return string|null
     */
    public function getLocalProperShippingName()
    {
        return $this->container['localProperShippingName'];
    }

    /**
     * Sets localProperShippingName
     *
     * @param string|null $localProperShippingName Local proper shipping name
     *
     * @return self
     */
    public function setLocalProperShippingName($localProperShippingName)
    {
        if (is_null($localProperShippingName)) {
            $this->openAPINullablesSetToNull[] = 'localProperShippingName';
        } else {
            $nullablesSetToNull = $this->openAPINullablesSetToNull;
            $index = array_search('localProperShippingName', $nullablesSetToNull, true);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['localProperShippingName'] = $localProperShippingName;

        return $this;
    }

    /**
     * Gets transportCategory
     *
     * @return string|null
     */
    public function getTransportCategory()
    {
        return $this->container['transportCategory'];
    }

    /**
     * Sets transportCategory
     *
     * @param string|null $transportCategory Transport category for ADR regulations
     *
     * @return self
     */
    public function setTransportCategory($transportCategory)
    {
        if (is_null($transportCategory)) {
            $this->openAPINullablesSetToNull[] = 'transportCategory';
        } else {
            $nullablesSetToNull = $this->openAPINullablesSetToNull;
            $index = array_search('transportCategory', $nullablesSetToNull, true);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['transportCategory'] = $transportCategory;

        return $this;
    }

    /**
     * Gets tunnelRestrictionCode
     *
     * @return string|null
     */
    public function getTunnelRestrictionCode()
    {
        return $this->container['tunnelRestrictionCode'];
    }

    /**
     * Sets tunnelRestrictionCode
     *
     * @param string|null $tunnelRestrictionCode Tunnel restriction code
     *
     * @return self
     */
    public function setTunnelRestrictionCode($tunnelRestrictionCode)
    {
        if (is_null($tunnelRestrictionCode)) {
            $this->openAPINullablesSetToNull[] = 'tunnelRestrictionCode';
        } else {
            $nullablesSetToNull = $this->openAPINullablesSetToNull;
            $index = array_search('tunnelRestrictionCode', $nullablesSetToNull, true);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['tunnelRestrictionCode'] = $tunnelRestrictionCode;

        return $this;
    }

    /**
     * Gets weightType
     *
     * @return string|null
     */
    public function getWeightType()
    {
        return $this->container['weightType'];
    }

    /**
     * Sets weightType
     *
     * @param string|null $weightType Type of weight measurement
     *
     * @return self
     */
    public function setWeightType($weightType)
    {
        if (is_null($weightType)) {
            throw new \InvalidArgumentException('non-nullable weightType cannot be null');
        }

        $allowedValues = $this->getWeightTypeAllowableValues();
        if (!in_array($weightType, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'weightType', must be one of '%s'",
                    $weightType,
                    implode("', '", $allowedValues)
                )
            );
        }

        $this->container['weightType'] = $weightType;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     */
    public function __toString(): string
    {
        return (string) json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
