<?php

declare(strict_types=1);

/**
 * DHLPickupCreate
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Toppy\Sendcloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
/**
 * Sendcloud Public REST API
 *
 * Complete Sendcloud API v2 specification - merged from official Stoplight documentation bundles
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendcloud.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
namespace Toppy\Sendcloud\Model;

use \ArrayAccess;
use \Toppy\Sendcloud\ObjectSerializer;

/**
 * DHLPickupCreate Class Doc Comment
 *
 * @category Class
 * @description 
 * @package  Toppy\Sendcloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class DHLPickupCreate implements ModelInterface, ArrayAccess, \JsonSerializable, \Stringable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'DHLPickupCreate';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'city' => 'string',
        'name' => 'string',
        'countryState' => 'string',
        'companyName' => 'string',
        'country' => 'string',
        'email' => 'string',
        'address' => 'string',
        'address2' => 'string',
        'pickupFrom' => '\DateTime',
        'pickupUntil' => '\DateTime',
        'postalCode' => 'string',
        'quantity' => 'int',
        'palletQuantity' => 'int',
        'telephone' => 'string',
        'totalWeight' => 'string',
        'reference' => 'string',
        'specialInstructions' => 'string',
        'carrier' => 'string',
        'contract' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'city' => null,
        'name' => null,
        'countryState' => null,
        'companyName' => null,
        'country' => null,
        'email' => 'email',
        'address' => null,
        'address2' => null,
        'pickupFrom' => 'date-time',
        'pickupUntil' => 'date-time',
        'postalCode' => null,
        'quantity' => 'int64',
        'palletQuantity' => 'int64',
        'telephone' => null,
        'totalWeight' => null,
        'reference' => null,
        'specialInstructions' => null,
        'carrier' => null,
        'contract' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'city' => false,
        'name' => false,
        'countryState' => true,
        'companyName' => false,
        'country' => false,
        'email' => true,
        'address' => false,
        'address2' => true,
        'pickupFrom' => false,
        'pickupUntil' => true,
        'postalCode' => false,
        'quantity' => false,
        'palletQuantity' => false,
        'telephone' => false,
        'totalWeight' => false,
        'reference' => true,
        'specialInstructions' => true,
        'carrier' => false,
        'contract' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->openAPINullablesSetToNull, true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'city' => 'city',
        'name' => 'name',
        'countryState' => 'country_state',
        'companyName' => 'company_name',
        'country' => 'country',
        'email' => 'email',
        'address' => 'address',
        'address2' => 'address_2',
        'pickupFrom' => 'pickup_from',
        'pickupUntil' => 'pickup_until',
        'postalCode' => 'postal_code',
        'quantity' => 'quantity',
        'palletQuantity' => 'pallet_quantity',
        'telephone' => 'telephone',
        'totalWeight' => 'total_weight',
        'reference' => 'reference',
        'specialInstructions' => 'special_instructions',
        'carrier' => 'carrier',
        'contract' => 'contract'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'city' => 'setCity',
        'name' => 'setName',
        'countryState' => 'setCountryState',
        'companyName' => 'setCompanyName',
        'country' => 'setCountry',
        'email' => 'setEmail',
        'address' => 'setAddress',
        'address2' => 'setAddress2',
        'pickupFrom' => 'setPickupFrom',
        'pickupUntil' => 'setPickupUntil',
        'postalCode' => 'setPostalCode',
        'quantity' => 'setQuantity',
        'palletQuantity' => 'setPalletQuantity',
        'telephone' => 'setTelephone',
        'totalWeight' => 'setTotalWeight',
        'reference' => 'setReference',
        'specialInstructions' => 'setSpecialInstructions',
        'carrier' => 'setCarrier',
        'contract' => 'setContract'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'city' => 'getCity',
        'name' => 'getName',
        'countryState' => 'getCountryState',
        'companyName' => 'getCompanyName',
        'country' => 'getCountry',
        'email' => 'getEmail',
        'address' => 'getAddress',
        'address2' => 'getAddress2',
        'pickupFrom' => 'getPickupFrom',
        'pickupUntil' => 'getPickupUntil',
        'postalCode' => 'getPostalCode',
        'quantity' => 'getQuantity',
        'palletQuantity' => 'getPalletQuantity',
        'telephone' => 'getTelephone',
        'totalWeight' => 'getTotalWeight',
        'reference' => 'getReference',
        'specialInstructions' => 'getSpecialInstructions',
        'carrier' => 'getCarrier',
        'contract' => 'getContract'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const COUNTRY_NL = 'NL';

    public const COUNTRY_BE = 'BE';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCountryAllowableValues()
    {
        return [
            self::COUNTRY_NL,
            self::COUNTRY_BE,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('city', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('countryState', $data ?? [], null);
        $this->setIfExists('companyName', $data ?? [], null);
        $this->setIfExists('country', $data ?? [], null);
        $this->setIfExists('email', $data ?? [], null);
        $this->setIfExists('address', $data ?? [], null);
        $this->setIfExists('address2', $data ?? [], null);
        $this->setIfExists('pickupFrom', $data ?? [], null);
        $this->setIfExists('pickupUntil', $data ?? [], null);
        $this->setIfExists('postalCode', $data ?? [], null);
        $this->setIfExists('quantity', $data ?? [], null);
        $this->setIfExists('palletQuantity', $data ?? [], null);
        $this->setIfExists('telephone', $data ?? [], null);
        $this->setIfExists('totalWeight', $data ?? [], null);
        $this->setIfExists('reference', $data ?? [], null);
        $this->setIfExists('specialInstructions', $data ?? [], null);
        $this->setIfExists('carrier', $data ?? [], null);
        $this->setIfExists('contract', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param mixed  $defaultValue
     * @param array<string, mixed> $fields
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['city'] === null) {
            $invalidProperties[] = "'city' can't be null";
        }

        if ((mb_strlen((string) $this->container['city']) < 1)) {
            $invalidProperties[] = "invalid value for 'city', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }

        if ((mb_strlen((string) $this->container['name']) < 1)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['countryState']) && (mb_strlen($this->container['countryState']) < 1)) {
            $invalidProperties[] = "invalid value for 'countryState', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['companyName'] === null) {
            $invalidProperties[] = "'companyName' can't be null";
        }

        if ((mb_strlen((string) $this->container['companyName']) < 1)) {
            $invalidProperties[] = "invalid value for 'companyName', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['country'] === null) {
            $invalidProperties[] = "'country' can't be null";
        }

        $allowedValues = $this->getCountryAllowableValues();
        if (!is_null($this->container['country']) && !in_array($this->container['country'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'country', must be one of '%s'",
                $this->container['country'],
                implode("', '", $allowedValues)
            );
        }

        if ((mb_strlen((string) $this->container['country']) > 2)) {
            $invalidProperties[] = "invalid value for 'country', the character length must be smaller than or equal to 2.";
        }

        if ((mb_strlen((string) $this->container['country']) < 2)) {
            $invalidProperties[] = "invalid value for 'country', the character length must be bigger than or equal to 2.";
        }

        if (!is_null($this->container['email']) && (mb_strlen($this->container['email']) < 1)) {
            $invalidProperties[] = "invalid value for 'email', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['address'] === null) {
            $invalidProperties[] = "'address' can't be null";
        }

        if ((mb_strlen((string) $this->container['address']) < 1)) {
            $invalidProperties[] = "invalid value for 'address', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['address2']) && (mb_strlen($this->container['address2']) < 0)) {
            $invalidProperties[] = "invalid value for 'address2', the character length must be bigger than or equal to 0.";
        }

        if ($this->container['pickupFrom'] === null) {
            $invalidProperties[] = "'pickupFrom' can't be null";
        }

        if ((mb_strlen((string) $this->container['pickupFrom']) < 1)) {
            $invalidProperties[] = "invalid value for 'pickupFrom', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['pickupUntil']) && (mb_strlen($this->container['pickupUntil']) < 1)) {
            $invalidProperties[] = "invalid value for 'pickupUntil', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['postalCode'] === null) {
            $invalidProperties[] = "'postalCode' can't be null";
        }

        if ((mb_strlen((string) $this->container['postalCode']) < 1)) {
            $invalidProperties[] = "invalid value for 'postalCode', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['quantity']) && ($this->container['quantity'] > 99)) {
            $invalidProperties[] = "invalid value for 'quantity', must be smaller than or equal to 99.";
        }

        if (!is_null($this->container['quantity']) && ($this->container['quantity'] < 0)) {
            $invalidProperties[] = "invalid value for 'quantity', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['palletQuantity']) && ($this->container['palletQuantity'] > 5)) {
            $invalidProperties[] = "invalid value for 'palletQuantity', must be smaller than or equal to 5.";
        }

        if (!is_null($this->container['palletQuantity']) && ($this->container['palletQuantity'] < 0)) {
            $invalidProperties[] = "invalid value for 'palletQuantity', must be bigger than or equal to 0.";
        }

        if ($this->container['telephone'] === null) {
            $invalidProperties[] = "'telephone' can't be null";
        }

        if ($this->container['totalWeight'] === null) {
            $invalidProperties[] = "'totalWeight' can't be null";
        }

        if (!is_null($this->container['reference']) && (mb_strlen($this->container['reference']) < 0)) {
            $invalidProperties[] = "invalid value for 'reference', the character length must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['specialInstructions']) && (mb_strlen($this->container['specialInstructions']) < 1)) {
            $invalidProperties[] = "invalid value for 'specialInstructions', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['carrier'] === null) {
            $invalidProperties[] = "'carrier' can't be null";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets city
     *
     * @return string
     */
    public function getCity()
    {
        return $this->container['city'];
    }

    /**
     * Sets city
     *
     * @param string $city city
     *
     * @return self
     */
    public function setCity($city)
    {
        if (is_null($city)) {
            throw new \InvalidArgumentException('non-nullable city cannot be null');
        }

        if ((mb_strlen($city) < 1)) {
            throw new \InvalidArgumentException('invalid length for $city when calling DHLPickupCreate., must be bigger than or equal to 1.');
        }

        $this->container['city'] = $city;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Contact person name.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }

        if ((mb_strlen($name) < 1)) {
            throw new \InvalidArgumentException('invalid length for $name when calling DHLPickupCreate., must be bigger than or equal to 1.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets countryState
     *
     * @return string|null
     */
    public function getCountryState()
    {
        return $this->container['countryState'];
    }

    /**
     * Sets countryState
     *
     * @param string|null $countryState countryState
     *
     * @return self
     */
    public function setCountryState($countryState)
    {
        if (is_null($countryState)) {
            $this->openAPINullablesSetToNull[] = 'countryState';
        } else {
            $nullablesSetToNull = $this->openAPINullablesSetToNull;
            $index = array_search('countryState', $nullablesSetToNull, true);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($countryState) && (mb_strlen($countryState) < 1)) {
            throw new \InvalidArgumentException('invalid length for $countryState when calling DHLPickupCreate., must be bigger than or equal to 1.');
        }

        $this->container['countryState'] = $countryState;

        return $this;
    }

    /**
     * Gets companyName
     *
     * @return string
     */
    public function getCompanyName()
    {
        return $this->container['companyName'];
    }

    /**
     * Sets companyName
     *
     * @param string $companyName Pickup address company name.
     *
     * @return self
     */
    public function setCompanyName($companyName)
    {
        if (is_null($companyName)) {
            throw new \InvalidArgumentException('non-nullable companyName cannot be null');
        }

        if ((mb_strlen($companyName) < 1)) {
            throw new \InvalidArgumentException('invalid length for $companyName when calling DHLPickupCreate., must be bigger than or equal to 1.');
        }

        $this->container['companyName'] = $companyName;

        return $this;
    }

    /**
     * Gets country
     *
     * @return string
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     *
     * @param string $country ISO 3166-1 alpha-2 country code.
     *
     * @return self
     */
    public function setCountry($country)
    {
        if (is_null($country)) {
            throw new \InvalidArgumentException('non-nullable country cannot be null');
        }

        $allowedValues = $this->getCountryAllowableValues();
        if (!in_array($country, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'country', must be one of '%s'",
                    $country,
                    implode("', '", $allowedValues)
                )
            );
        }

        if ((mb_strlen($country) > 2)) {
            throw new \InvalidArgumentException('invalid length for $country when calling DHLPickupCreate., must be smaller than or equal to 2.');
        }

        if ((mb_strlen($country) < 2)) {
            throw new \InvalidArgumentException('invalid length for $country when calling DHLPickupCreate., must be bigger than or equal to 2.');
        }

        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string|null
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string|null $email Contact person email.
     *
     * @return self
     */
    public function setEmail($email)
    {
        if (is_null($email)) {
            $this->openAPINullablesSetToNull[] = 'email';
        } else {
            $nullablesSetToNull = $this->openAPINullablesSetToNull;
            $index = array_search('email', $nullablesSetToNull, true);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($email) && (mb_strlen($email) < 1)) {
            throw new \InvalidArgumentException('invalid length for $email when calling DHLPickupCreate., must be bigger than or equal to 1.');
        }

        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets address
     *
     * @return string
     */
    public function getAddress()
    {
        return $this->container['address'];
    }

    /**
     * Sets address
     *
     * @param string $address Address line 1 of the pickup, this should include the house number.
     *
     * @return self
     */
    public function setAddress($address)
    {
        if (is_null($address)) {
            throw new \InvalidArgumentException('non-nullable address cannot be null');
        }

        if ((mb_strlen($address) < 1)) {
            throw new \InvalidArgumentException('invalid length for $address when calling DHLPickupCreate., must be bigger than or equal to 1.');
        }

        $this->container['address'] = $address;

        return $this;
    }

    /**
     * Gets address2
     *
     * @return string|null
     */
    public function getAddress2()
    {
        return $this->container['address2'];
    }

    /**
     * Sets address2
     *
     * @param string|null $address2 Address line 2 of the pickup.
     *
     * @return self
     */
    public function setAddress2($address2)
    {
        if (is_null($address2)) {
            $this->openAPINullablesSetToNull[] = 'address2';
        } else {
            $nullablesSetToNull = $this->openAPINullablesSetToNull;
            $index = array_search('address2', $nullablesSetToNull, true);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($address2) && (mb_strlen($address2) < 0)) {
            throw new \InvalidArgumentException('invalid length for $address2 when calling DHLPickupCreate., must be bigger than or equal to 0.');
        }

        $this->container['address2'] = $address2;

        return $this;
    }

    /**
     * Gets pickupFrom
     *
     * @return \DateTime
     */
    public function getPickupFrom()
    {
        return $this->container['pickupFrom'];
    }

    /**
     * Sets pickupFrom
     *
     * @param \DateTime $pickupFrom ISO 8601 DateTime that indicates from what time the pickup can take place. Preferably specified in UTC. When no timezone information is specified, we will use the timezone of the user their invoice address country.
     *
     * @return self
     */
    public function setPickupFrom($pickupFrom)
    {
        if (is_null($pickupFrom)) {
            throw new \InvalidArgumentException('non-nullable pickupFrom cannot be null');
        }

        if ((mb_strlen($pickupFrom) < 1)) {
            throw new \InvalidArgumentException('invalid length for $pickupFrom when calling DHLPickupCreate., must be bigger than or equal to 1.');
        }

        $this->container['pickupFrom'] = $pickupFrom;

        return $this;
    }

    /**
     * Gets pickupUntil
     *
     * @return \DateTime|null
     */
    public function getPickupUntil()
    {
        return $this->container['pickupUntil'];
    }

    /**
     * Sets pickupUntil
     *
     * @param \DateTime|null $pickupUntil ISO 8601 DateTime that indicates until what time the pickup can take place. Preferably specified in UTC. When no timezone information is specified, we will use the timezone of the user their invoice address country.
     *
     * @return self
     */
    public function setPickupUntil($pickupUntil)
    {
        if (is_null($pickupUntil)) {
            $this->openAPINullablesSetToNull[] = 'pickupUntil';
        } else {
            $nullablesSetToNull = $this->openAPINullablesSetToNull;
            $index = array_search('pickupUntil', $nullablesSetToNull, true);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($pickupUntil) && (mb_strlen($pickupUntil) < 1)) {
            throw new \InvalidArgumentException('invalid length for $pickupUntil when calling DHLPickupCreate., must be bigger than or equal to 1.');
        }

        $this->container['pickupUntil'] = $pickupUntil;

        return $this;
    }

    /**
     * Gets postalCode
     *
     * @return string
     */
    public function getPostalCode()
    {
        return $this->container['postalCode'];
    }

    /**
     * Sets postalCode
     *
     * @param string $postalCode postalCode
     *
     * @return self
     */
    public function setPostalCode($postalCode)
    {
        if (is_null($postalCode)) {
            throw new \InvalidArgumentException('non-nullable postalCode cannot be null');
        }

        if ((mb_strlen($postalCode) < 1)) {
            throw new \InvalidArgumentException('invalid length for $postalCode when calling DHLPickupCreate., must be bigger than or equal to 1.');
        }

        $this->container['postalCode'] = $postalCode;

        return $this;
    }

    /**
     * Gets quantity
     *
     * @return int|null
     */
    public function getQuantity()
    {
        return $this->container['quantity'];
    }

    /**
     * Sets quantity
     *
     * @param int|null $quantity Number of parcels that should be picked up. The number of parcels or the number of pallets must be specified.
     *
     * @return self
     */
    public function setQuantity($quantity)
    {
        if (is_null($quantity)) {
            throw new \InvalidArgumentException('non-nullable quantity cannot be null');
        }

        if (($quantity > 99)) {
            throw new \InvalidArgumentException('invalid value for $quantity when calling DHLPickupCreate., must be smaller than or equal to 99.');
        }

        if (($quantity < 0)) {
            throw new \InvalidArgumentException('invalid value for $quantity when calling DHLPickupCreate., must be bigger than or equal to 0.');
        }

        $this->container['quantity'] = $quantity;

        return $this;
    }

    /**
     * Gets palletQuantity
     *
     * @return int|null
     */
    public function getPalletQuantity()
    {
        return $this->container['palletQuantity'];
    }

    /**
     * Sets palletQuantity
     *
     * @param int|null $palletQuantity Number of pallets that should be picked up.The number of parcels or the number of pallets must be specified.
     *
     * @return self
     */
    public function setPalletQuantity($palletQuantity)
    {
        if (is_null($palletQuantity)) {
            throw new \InvalidArgumentException('non-nullable palletQuantity cannot be null');
        }

        if (($palletQuantity > 5)) {
            throw new \InvalidArgumentException('invalid value for $palletQuantity when calling DHLPickupCreate., must be smaller than or equal to 5.');
        }

        if (($palletQuantity < 0)) {
            throw new \InvalidArgumentException('invalid value for $palletQuantity when calling DHLPickupCreate., must be bigger than or equal to 0.');
        }

        $this->container['palletQuantity'] = $palletQuantity;

        return $this;
    }

    /**
     * Gets telephone
     *
     * @return string
     */
    public function getTelephone()
    {
        return $this->container['telephone'];
    }

    /**
     * Sets telephone
     *
     * @param string $telephone Contact person telephone number.
     *
     * @return self
     */
    public function setTelephone($telephone)
    {
        if (is_null($telephone)) {
            throw new \InvalidArgumentException('non-nullable telephone cannot be null');
        }

        $this->container['telephone'] = $telephone;

        return $this;
    }

    /**
     * Gets totalWeight
     *
     * @return string
     */
    public function getTotalWeight()
    {
        return $this->container['totalWeight'];
    }

    /**
     * Sets totalWeight
     *
     * @param string $totalWeight Total weight in kilograms.
     *
     * @return self
     */
    public function setTotalWeight($totalWeight)
    {
        if (is_null($totalWeight)) {
            throw new \InvalidArgumentException('non-nullable totalWeight cannot be null');
        }

        $this->container['totalWeight'] = $totalWeight;

        return $this;
    }

    /**
     * Gets reference
     *
     * @return string|null
     */
    public function getReference()
    {
        return $this->container['reference'];
    }

    /**
     * Sets reference
     *
     * @param string|null $reference A reference number for your own administration.
     *
     * @return self
     */
    public function setReference($reference)
    {
        if (is_null($reference)) {
            $this->openAPINullablesSetToNull[] = 'reference';
        } else {
            $nullablesSetToNull = $this->openAPINullablesSetToNull;
            $index = array_search('reference', $nullablesSetToNull, true);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($reference) && (mb_strlen($reference) < 0)) {
            throw new \InvalidArgumentException('invalid length for $reference when calling DHLPickupCreate., must be bigger than or equal to 0.');
        }

        $this->container['reference'] = $reference;

        return $this;
    }

    /**
     * Gets specialInstructions
     *
     * @return string|null
     */
    public function getSpecialInstructions()
    {
        return $this->container['specialInstructions'];
    }

    /**
     * Sets specialInstructions
     *
     * @param string|null $specialInstructions Special instructions that the driver should take into account.
     *
     * @return self
     */
    public function setSpecialInstructions($specialInstructions)
    {
        if (is_null($specialInstructions)) {
            $this->openAPINullablesSetToNull[] = 'specialInstructions';
        } else {
            $nullablesSetToNull = $this->openAPINullablesSetToNull;
            $index = array_search('specialInstructions', $nullablesSetToNull, true);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($specialInstructions) && (mb_strlen($specialInstructions) < 1)) {
            throw new \InvalidArgumentException('invalid length for $specialInstructions when calling DHLPickupCreate., must be bigger than or equal to 1.');
        }

        $this->container['specialInstructions'] = $specialInstructions;

        return $this;
    }

    /**
     * Gets carrier
     *
     * @return string
     */
    public function getCarrier()
    {
        return $this->container['carrier'];
    }

    /**
     * Sets carrier
     *
     * @param string $carrier The user selected carrier code for the pickup.
     *
     * @return self
     */
    public function setCarrier($carrier)
    {
        if (is_null($carrier)) {
            throw new \InvalidArgumentException('non-nullable carrier cannot be null');
        }

        $this->container['carrier'] = $carrier;

        return $this;
    }

    /**
     * Gets contract
     *
     * @return int|null
     */
    public function getContract()
    {
        return $this->container['contract'];
    }

    /**
     * Sets contract
     *
     * @param int|null $contract Id of the contract you want to be used for pickup request.
     *
     * @return self
     */
    public function setContract($contract)
    {
        if (is_null($contract)) {
            $this->openAPINullablesSetToNull[] = 'contract';
        } else {
            $nullablesSetToNull = $this->openAPINullablesSetToNull;
            $index = array_search('contract', $nullablesSetToNull, true);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['contract'] = $contract;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     */
    public function __toString(): string
    {
        return (string) json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
