<?php

declare(strict_types=1);

/**
 * ModelReturn
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Toppy\Sendcloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
/**
 * Sendcloud Public REST API
 *
 * Complete Sendcloud API v2 specification - merged from official Stoplight documentation bundles
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendcloud.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
namespace Toppy\Sendcloud\Model;

use \ArrayAccess;
use \Toppy\Sendcloud\ObjectSerializer;

/**
 * ModelReturn Class Doc Comment
 *
 * @category Class
 * @description An object representing a Return.  This includes details of the original outgoing parcel, the incoming parcel and the returned items.
 * @package  Toppy\Sendcloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ModelReturn implements ModelInterface, ArrayAccess, \JsonSerializable, \Stringable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Return';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'int',
        'createdAt' => '\DateTime',
        'reason' => 'int',
        'outgoingParcel' => 'int',
        'incomingParcel' => 'int',
        'message' => 'string',
        'refund' => \Toppy\Sendcloud\Model\ReturnRefund::class,
        'isCancellable' => 'bool',
        'returnFee' => 'float',
        'returnFeeCurrency' => 'string',
        'labelCost' => 'float',
        'labelCurrency' => 'string',
        'itemsCost' => 'float',
        'deliveredAt' => '\DateTime',
        'deliveryOption' => 'string',
        'storeLocation' => 'int',
        'outgoingParcelData' => \Toppy\Sendcloud\Model\ReturnParcel::class,
        'incomingParcelData' => \Toppy\Sendcloud\Model\ReturnIncomingParcelData::class,
        'incomingParcelStatus' => \Toppy\Sendcloud\Model\ReturnIncomingParcelStatus::class,
        'images' => '\Toppy\Sendcloud\Model\ReturnImageObject[]',
        'ruleModifications' => '\Toppy\Sendcloud\Model\ReturnRuleModificationsInner[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'createdAt' => 'date-time',
        'reason' => null,
        'outgoingParcel' => null,
        'incomingParcel' => null,
        'message' => null,
        'refund' => null,
        'isCancellable' => null,
        'returnFee' => null,
        'returnFeeCurrency' => null,
        'labelCost' => null,
        'labelCurrency' => null,
        'itemsCost' => null,
        'deliveredAt' => 'date-time',
        'deliveryOption' => null,
        'storeLocation' => null,
        'outgoingParcelData' => null,
        'incomingParcelData' => null,
        'incomingParcelStatus' => null,
        'images' => null,
        'ruleModifications' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'createdAt' => false,
        'reason' => false,
        'outgoingParcel' => false,
        'incomingParcel' => false,
        'message' => false,
        'refund' => false,
        'isCancellable' => false,
        'returnFee' => false,
        'returnFeeCurrency' => false,
        'labelCost' => false,
        'labelCurrency' => false,
        'itemsCost' => false,
        'deliveredAt' => false,
        'deliveryOption' => false,
        'storeLocation' => false,
        'outgoingParcelData' => false,
        'incomingParcelData' => false,
        'incomingParcelStatus' => false,
        'images' => false,
        'ruleModifications' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Checks if a property is nullable
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->openAPINullablesSetToNull, true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'createdAt' => 'created_at',
        'reason' => 'reason',
        'outgoingParcel' => 'outgoing_parcel',
        'incomingParcel' => 'incoming_parcel',
        'message' => 'message',
        'refund' => 'refund',
        'isCancellable' => 'is_cancellable',
        'returnFee' => 'return_fee',
        'returnFeeCurrency' => 'return_fee_currency',
        'labelCost' => 'label_cost',
        'labelCurrency' => 'label_currency',
        'itemsCost' => 'items_cost',
        'deliveredAt' => 'delivered_at',
        'deliveryOption' => 'delivery_option',
        'storeLocation' => 'store_location',
        'outgoingParcelData' => 'outgoing_parcel_data',
        'incomingParcelData' => 'incoming_parcel_data',
        'incomingParcelStatus' => 'incoming_parcel_status',
        'images' => 'images',
        'ruleModifications' => 'rule_modifications'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'createdAt' => 'setCreatedAt',
        'reason' => 'setReason',
        'outgoingParcel' => 'setOutgoingParcel',
        'incomingParcel' => 'setIncomingParcel',
        'message' => 'setMessage',
        'refund' => 'setRefund',
        'isCancellable' => 'setIsCancellable',
        'returnFee' => 'setReturnFee',
        'returnFeeCurrency' => 'setReturnFeeCurrency',
        'labelCost' => 'setLabelCost',
        'labelCurrency' => 'setLabelCurrency',
        'itemsCost' => 'setItemsCost',
        'deliveredAt' => 'setDeliveredAt',
        'deliveryOption' => 'setDeliveryOption',
        'storeLocation' => 'setStoreLocation',
        'outgoingParcelData' => 'setOutgoingParcelData',
        'incomingParcelData' => 'setIncomingParcelData',
        'incomingParcelStatus' => 'setIncomingParcelStatus',
        'images' => 'setImages',
        'ruleModifications' => 'setRuleModifications'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'createdAt' => 'getCreatedAt',
        'reason' => 'getReason',
        'outgoingParcel' => 'getOutgoingParcel',
        'incomingParcel' => 'getIncomingParcel',
        'message' => 'getMessage',
        'refund' => 'getRefund',
        'isCancellable' => 'getIsCancellable',
        'returnFee' => 'getReturnFee',
        'returnFeeCurrency' => 'getReturnFeeCurrency',
        'labelCost' => 'getLabelCost',
        'labelCurrency' => 'getLabelCurrency',
        'itemsCost' => 'getItemsCost',
        'deliveredAt' => 'getDeliveredAt',
        'deliveryOption' => 'getDeliveryOption',
        'storeLocation' => 'getStoreLocation',
        'outgoingParcelData' => 'getOutgoingParcelData',
        'incomingParcelData' => 'getIncomingParcelData',
        'incomingParcelStatus' => 'getIncomingParcelStatus',
        'images' => 'getImages',
        'ruleModifications' => 'getRuleModifications'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const DELIVERY_OPTION_DROP_OFF_POINT = 'drop_off_point';

    public const DELIVERY_OPTION_DROP_OFF_LABELLESS = 'drop_off_labelless';

    public const DELIVERY_OPTION_IN_STORE = 'in_store';

    public const DELIVERY_OPTION_PICKUP = 'pickup';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getDeliveryOptionAllowableValues()
    {
        return [
            self::DELIVERY_OPTION_DROP_OFF_POINT,
            self::DELIVERY_OPTION_DROP_OFF_LABELLESS,
            self::DELIVERY_OPTION_IN_STORE,
            self::DELIVERY_OPTION_PICKUP,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('createdAt', $data ?? [], null);
        $this->setIfExists('reason', $data ?? [], null);
        $this->setIfExists('outgoingParcel', $data ?? [], null);
        $this->setIfExists('incomingParcel', $data ?? [], null);
        $this->setIfExists('message', $data ?? [], null);
        $this->setIfExists('refund', $data ?? [], null);
        $this->setIfExists('isCancellable', $data ?? [], null);
        $this->setIfExists('returnFee', $data ?? [], null);
        $this->setIfExists('returnFeeCurrency', $data ?? [], null);
        $this->setIfExists('labelCost', $data ?? [], null);
        $this->setIfExists('labelCurrency', $data ?? [], null);
        $this->setIfExists('itemsCost', $data ?? [], null);
        $this->setIfExists('deliveredAt', $data ?? [], null);
        $this->setIfExists('deliveryOption', $data ?? [], null);
        $this->setIfExists('storeLocation', $data ?? [], null);
        $this->setIfExists('outgoingParcelData', $data ?? [], null);
        $this->setIfExists('incomingParcelData', $data ?? [], null);
        $this->setIfExists('incomingParcelStatus', $data ?? [], null);
        $this->setIfExists('images', $data ?? [], null);
        $this->setIfExists('ruleModifications', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param mixed  $defaultValue
     * @param array<string, mixed> $fields
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['id']) && ($this->container['id'] < 1)) {
            $invalidProperties[] = "invalid value for 'id', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['reason']) && ($this->container['reason'] < 1)) {
            $invalidProperties[] = "invalid value for 'reason', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['outgoingParcel']) && ($this->container['outgoingParcel'] < 1)) {
            $invalidProperties[] = "invalid value for 'outgoingParcel', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['incomingParcel']) && ($this->container['incomingParcel'] < 1)) {
            $invalidProperties[] = "invalid value for 'incomingParcel', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['returnFee']) && ($this->container['returnFee'] < 0)) {
            $invalidProperties[] = "invalid value for 'returnFee', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['labelCost']) && ($this->container['labelCost'] < 0)) {
            $invalidProperties[] = "invalid value for 'labelCost', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['itemsCost']) && ($this->container['itemsCost'] < 0)) {
            $invalidProperties[] = "invalid value for 'itemsCost', must be bigger than or equal to 0.";
        }

        $allowedValues = $this->getDeliveryOptionAllowableValues();
        if (!is_null($this->container['deliveryOption']) && !in_array($this->container['deliveryOption'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'deliveryOption', must be one of '%s'",
                $this->container['deliveryOption'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['storeLocation']) && ($this->container['storeLocation'] < 1)) {
            $invalidProperties[] = "invalid value for 'storeLocation', must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id The unique identifier of this Return object
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }

        if (($id < 1)) {
            throw new \InvalidArgumentException('invalid value for $id when calling ModelReturn., must be bigger than or equal to 1.');
        }

        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets createdAt
     *
     * @return \DateTime|null
     */
    public function getCreatedAt()
    {
        return $this->container['createdAt'];
    }

    /**
     * Sets createdAt
     *
     * @param \DateTime|null $createdAt The creation date of this Return, in ISO 8601 format
     *
     * @return self
     */
    public function setCreatedAt($createdAt)
    {
        if (is_null($createdAt)) {
            throw new \InvalidArgumentException('non-nullable createdAt cannot be null');
        }

        $this->container['createdAt'] = $createdAt;

        return $this;
    }

    /**
     * Gets reason
     *
     * @return int|null
     */
    public function getReason()
    {
        return $this->container['reason'];
    }

    /**
     * Sets reason
     *
     * @param int|null $reason Identifier of the reason for this return
     *
     * @return self
     */
    public function setReason($reason)
    {
        if (is_null($reason)) {
            throw new \InvalidArgumentException('non-nullable reason cannot be null');
        }

        if (($reason < 1)) {
            throw new \InvalidArgumentException('invalid value for $reason when calling ModelReturn., must be bigger than or equal to 1.');
        }

        $this->container['reason'] = $reason;

        return $this;
    }

    /**
     * Gets outgoingParcel
     *
     * @return int|null
     */
    public function getOutgoingParcel()
    {
        return $this->container['outgoingParcel'];
    }

    /**
     * Sets outgoingParcel
     *
     * @param int|null $outgoingParcel Identifier of the original outgoing Parcel object
     *
     * @return self
     */
    public function setOutgoingParcel($outgoingParcel)
    {
        if (is_null($outgoingParcel)) {
            throw new \InvalidArgumentException('non-nullable outgoingParcel cannot be null');
        }

        if (($outgoingParcel < 1)) {
            throw new \InvalidArgumentException('invalid value for $outgoingParcel when calling ModelReturn., must be bigger than or equal to 1.');
        }

        $this->container['outgoingParcel'] = $outgoingParcel;

        return $this;
    }

    /**
     * Gets incomingParcel
     *
     * @return int|null
     */
    public function getIncomingParcel()
    {
        return $this->container['incomingParcel'];
    }

    /**
     * Sets incomingParcel
     *
     * @param int|null $incomingParcel Identifier of the incoming return Parcel object
     *
     * @return self
     */
    public function setIncomingParcel($incomingParcel)
    {
        if (is_null($incomingParcel)) {
            throw new \InvalidArgumentException('non-nullable incomingParcel cannot be null');
        }

        if (($incomingParcel < 1)) {
            throw new \InvalidArgumentException('invalid value for $incomingParcel when calling ModelReturn., must be bigger than or equal to 1.');
        }

        $this->container['incomingParcel'] = $incomingParcel;

        return $this;
    }

    /**
     * Gets message
     *
     * @return string|null
     */
    public function getMessage()
    {
        return $this->container['message'];
    }

    /**
     * Sets message
     *
     * @param string|null $message Return reason message as written by the customer
     *
     * @return self
     */
    public function setMessage($message)
    {
        if (is_null($message)) {
            throw new \InvalidArgumentException('non-nullable message cannot be null');
        }

        $this->container['message'] = $message;

        return $this;
    }

    /**
     * Gets refund
     *
     * @return \Toppy\Sendcloud\Model\ReturnRefund|null
     */
    public function getRefund()
    {
        return $this->container['refund'];
    }

    /**
     * Sets refund
     *
     * @param \Toppy\Sendcloud\Model\ReturnRefund|null $refund refund
     *
     * @return self
     */
    public function setRefund($refund)
    {
        if (is_null($refund)) {
            throw new \InvalidArgumentException('non-nullable refund cannot be null');
        }

        $this->container['refund'] = $refund;

        return $this;
    }

    /**
     * Gets isCancellable
     *
     * @return bool|null
     */
    public function getIsCancellable()
    {
        return $this->container['isCancellable'];
    }

    /**
     * Sets isCancellable
     *
     * @param bool|null $isCancellable Whether the incoming return parcel can still be cancelled
     *
     * @return self
     */
    public function setIsCancellable($isCancellable)
    {
        if (is_null($isCancellable)) {
            throw new \InvalidArgumentException('non-nullable isCancellable cannot be null');
        }

        $this->container['isCancellable'] = $isCancellable;

        return $this;
    }

    /**
     * Gets returnFee
     *
     * @return float|null
     */
    public function getReturnFee()
    {
        return $this->container['returnFee'];
    }

    /**
     * Sets returnFee
     *
     * @param float|null $returnFee The fee associated with this return
     *
     * @return self
     */
    public function setReturnFee($returnFee)
    {
        if (is_null($returnFee)) {
            throw new \InvalidArgumentException('non-nullable returnFee cannot be null');
        }

        if (($returnFee < 0)) {
            throw new \InvalidArgumentException('invalid value for $returnFee when calling ModelReturn., must be bigger than or equal to 0.');
        }

        $this->container['returnFee'] = $returnFee;

        return $this;
    }

    /**
     * Gets returnFeeCurrency
     *
     * @return string|null
     */
    public function getReturnFeeCurrency()
    {
        return $this->container['returnFeeCurrency'];
    }

    /**
     * Sets returnFeeCurrency
     *
     * @param string|null $returnFeeCurrency Currency of the return fee in three-letter ISO 4217 format
     *
     * @return self
     */
    public function setReturnFeeCurrency($returnFeeCurrency)
    {
        if (is_null($returnFeeCurrency)) {
            throw new \InvalidArgumentException('non-nullable returnFeeCurrency cannot be null');
        }

        $this->container['returnFeeCurrency'] = $returnFeeCurrency;

        return $this;
    }

    /**
     * Gets labelCost
     *
     * @return float|null
     */
    public function getLabelCost()
    {
        return $this->container['labelCost'];
    }

    /**
     * Sets labelCost
     *
     * @param float|null $labelCost Cost of the label for the incoming return parcel
     *
     * @return self
     */
    public function setLabelCost($labelCost)
    {
        if (is_null($labelCost)) {
            throw new \InvalidArgumentException('non-nullable labelCost cannot be null');
        }

        if (($labelCost < 0)) {
            throw new \InvalidArgumentException('invalid value for $labelCost when calling ModelReturn., must be bigger than or equal to 0.');
        }

        $this->container['labelCost'] = $labelCost;

        return $this;
    }

    /**
     * Gets labelCurrency
     *
     * @return string|null
     */
    public function getLabelCurrency()
    {
        return $this->container['labelCurrency'];
    }

    /**
     * Sets labelCurrency
     *
     * @param string|null $labelCurrency Currency of the label cost in three-letter ISO 4217 format
     *
     * @return self
     */
    public function setLabelCurrency($labelCurrency)
    {
        if (is_null($labelCurrency)) {
            throw new \InvalidArgumentException('non-nullable labelCurrency cannot be null');
        }

        $this->container['labelCurrency'] = $labelCurrency;

        return $this;
    }

    /**
     * Gets itemsCost
     *
     * @return float|null
     */
    public function getItemsCost()
    {
        return $this->container['itemsCost'];
    }

    /**
     * Sets itemsCost
     *
     * @param float|null $itemsCost Total cost of the returned items
     *
     * @return self
     */
    public function setItemsCost($itemsCost)
    {
        if (is_null($itemsCost)) {
            throw new \InvalidArgumentException('non-nullable itemsCost cannot be null');
        }

        if (($itemsCost < 0)) {
            throw new \InvalidArgumentException('invalid value for $itemsCost when calling ModelReturn., must be bigger than or equal to 0.');
        }

        $this->container['itemsCost'] = $itemsCost;

        return $this;
    }

    /**
     * Gets deliveredAt
     *
     * @return \DateTime|null
     */
    public function getDeliveredAt()
    {
        return $this->container['deliveredAt'];
    }

    /**
     * Sets deliveredAt
     *
     * @param \DateTime|null $deliveredAt Delivery date of the incoming return parcel
     *
     * @return self
     */
    public function setDeliveredAt($deliveredAt)
    {
        if (is_null($deliveredAt)) {
            throw new \InvalidArgumentException('non-nullable deliveredAt cannot be null');
        }

        $this->container['deliveredAt'] = $deliveredAt;

        return $this;
    }

    /**
     * Gets deliveryOption
     *
     * @return string|null
     */
    public function getDeliveryOption()
    {
        return $this->container['deliveryOption'];
    }

    /**
     * Sets deliveryOption
     *
     * @param string|null $deliveryOption The options the customer has for returning this parcel:  * drop\\_off\\_point: At a drop-off point - Print at home  * drop\\_off\\_labelless: At a drop-off point - No printer needed  * in\\_store: Return in store  * pickup: Arrange a pick-up
     *
     * @return self
     */
    public function setDeliveryOption($deliveryOption)
    {
        if (is_null($deliveryOption)) {
            throw new \InvalidArgumentException('non-nullable deliveryOption cannot be null');
        }

        $allowedValues = $this->getDeliveryOptionAllowableValues();
        if (!in_array($deliveryOption, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'deliveryOption', must be one of '%s'",
                    $deliveryOption,
                    implode("', '", $allowedValues)
                )
            );
        }

        $this->container['deliveryOption'] = $deliveryOption;

        return $this;
    }

    /**
     * Gets storeLocation
     *
     * @return int|null
     */
    public function getStoreLocation()
    {
        return $this->container['storeLocation'];
    }

    /**
     * Sets storeLocation
     *
     * @param int|null $storeLocation The identifier of the in-store return address
     *
     * @return self
     */
    public function setStoreLocation($storeLocation)
    {
        if (is_null($storeLocation)) {
            throw new \InvalidArgumentException('non-nullable storeLocation cannot be null');
        }

        if (($storeLocation < 1)) {
            throw new \InvalidArgumentException('invalid value for $storeLocation when calling ModelReturn., must be bigger than or equal to 1.');
        }

        $this->container['storeLocation'] = $storeLocation;

        return $this;
    }

    /**
     * Gets outgoingParcelData
     *
     * @return \Toppy\Sendcloud\Model\ReturnParcel|null
     */
    public function getOutgoingParcelData()
    {
        return $this->container['outgoingParcelData'];
    }

    /**
     * Sets outgoingParcelData
     *
     * @param \Toppy\Sendcloud\Model\ReturnParcel|null $outgoingParcelData outgoingParcelData
     *
     * @return self
     */
    public function setOutgoingParcelData($outgoingParcelData)
    {
        if (is_null($outgoingParcelData)) {
            throw new \InvalidArgumentException('non-nullable outgoingParcelData cannot be null');
        }

        $this->container['outgoingParcelData'] = $outgoingParcelData;

        return $this;
    }

    /**
     * Gets incomingParcelData
     *
     * @return \Toppy\Sendcloud\Model\ReturnIncomingParcelData|null
     */
    public function getIncomingParcelData()
    {
        return $this->container['incomingParcelData'];
    }

    /**
     * Sets incomingParcelData
     *
     * @param \Toppy\Sendcloud\Model\ReturnIncomingParcelData|null $incomingParcelData incomingParcelData
     *
     * @return self
     */
    public function setIncomingParcelData($incomingParcelData)
    {
        if (is_null($incomingParcelData)) {
            throw new \InvalidArgumentException('non-nullable incomingParcelData cannot be null');
        }

        $this->container['incomingParcelData'] = $incomingParcelData;

        return $this;
    }

    /**
     * Gets incomingParcelStatus
     *
     * @return \Toppy\Sendcloud\Model\ReturnIncomingParcelStatus|null
     */
    public function getIncomingParcelStatus()
    {
        return $this->container['incomingParcelStatus'];
    }

    /**
     * Sets incomingParcelStatus
     *
     * @param \Toppy\Sendcloud\Model\ReturnIncomingParcelStatus|null $incomingParcelStatus incomingParcelStatus
     *
     * @return self
     */
    public function setIncomingParcelStatus($incomingParcelStatus)
    {
        if (is_null($incomingParcelStatus)) {
            throw new \InvalidArgumentException('non-nullable incomingParcelStatus cannot be null');
        }

        $this->container['incomingParcelStatus'] = $incomingParcelStatus;

        return $this;
    }

    /**
     * Gets images
     *
     * @return \Toppy\Sendcloud\Model\ReturnImageObject[]|null
     */
    public function getImages()
    {
        return $this->container['images'];
    }

    /**
     * Sets images
     *
     * @param \Toppy\Sendcloud\Model\ReturnImageObject[]|null $images A list of images attached to a return
     *
     * @return self
     */
    public function setImages($images)
    {
        if (is_null($images)) {
            throw new \InvalidArgumentException('non-nullable images cannot be null');
        }

        $this->container['images'] = $images;

        return $this;
    }

    /**
     * Gets ruleModifications
     *
     * @return \Toppy\Sendcloud\Model\ReturnRuleModificationsInner[]|null
     */
    public function getRuleModifications()
    {
        return $this->container['ruleModifications'];
    }

    /**
     * Sets ruleModifications
     *
     * @param \Toppy\Sendcloud\Model\ReturnRuleModificationsInner[]|null $ruleModifications List of return rules applied to this Return
     *
     * @return self
     */
    public function setRuleModifications($ruleModifications)
    {
        if (is_null($ruleModifications)) {
            throw new \InvalidArgumentException('non-nullable ruleModifications cannot be null');
        }

        $this->container['ruleModifications'] = $ruleModifications;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     */
    public function __toString(): string
    {
        return (string) json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
