<?php

declare(strict_types=1);

/**
 * ReturnCreatedWebhookData
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Toppy\Sendcloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
/**
 * Sendcloud Public REST API
 *
 * Complete Sendcloud API v2 specification - merged from official Stoplight documentation bundles
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendcloud.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
namespace Toppy\Sendcloud\Model;

use \ArrayAccess;
use \Toppy\Sendcloud\ObjectSerializer;

/**
 * ReturnCreatedWebhookData Class Doc Comment
 *
 * @category Class
 * @description Information about the return
 * @package  Toppy\Sendcloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ReturnCreatedWebhookData implements ModelInterface, ArrayAccess, \JsonSerializable, \Stringable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ReturnCreatedWebhook_data';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'float',
        'brandId' => 'int',
        'orderNumber' => 'string',
        'returnReasonId' => 'int',
        'returnAddressId' => 'int',
        'paidReturn' => 'bool',
        'deliveryChoice' => 'string',
        'refundType' => 'string',
        'items' => '\Toppy\Sendcloud\Model\ReturnCreatedWebhookDataItemsInner[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'brandId' => null,
        'orderNumber' => null,
        'returnReasonId' => null,
        'returnAddressId' => null,
        'paidReturn' => null,
        'deliveryChoice' => null,
        'refundType' => null,
        'items' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'brandId' => false,
        'orderNumber' => false,
        'returnReasonId' => false,
        'returnAddressId' => false,
        'paidReturn' => false,
        'deliveryChoice' => false,
        'refundType' => false,
        'items' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Checks if a property is nullable
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->openAPINullablesSetToNull, true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'brandId' => 'brand_id',
        'orderNumber' => 'order_number',
        'returnReasonId' => 'return_reason_id',
        'returnAddressId' => 'return_address_id',
        'paidReturn' => 'paid_return',
        'deliveryChoice' => 'delivery_choice',
        'refundType' => 'refund_type',
        'items' => 'items'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'brandId' => 'setBrandId',
        'orderNumber' => 'setOrderNumber',
        'returnReasonId' => 'setReturnReasonId',
        'returnAddressId' => 'setReturnAddressId',
        'paidReturn' => 'setPaidReturn',
        'deliveryChoice' => 'setDeliveryChoice',
        'refundType' => 'setRefundType',
        'items' => 'setItems'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'brandId' => 'getBrandId',
        'orderNumber' => 'getOrderNumber',
        'returnReasonId' => 'getReturnReasonId',
        'returnAddressId' => 'getReturnAddressId',
        'paidReturn' => 'getPaidReturn',
        'deliveryChoice' => 'getDeliveryChoice',
        'refundType' => 'getRefundType',
        'items' => 'getItems'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('brandId', $data ?? [], null);
        $this->setIfExists('orderNumber', $data ?? [], null);
        $this->setIfExists('returnReasonId', $data ?? [], null);
        $this->setIfExists('returnAddressId', $data ?? [], null);
        $this->setIfExists('paidReturn', $data ?? [], null);
        $this->setIfExists('deliveryChoice', $data ?? [], null);
        $this->setIfExists('refundType', $data ?? [], null);
        $this->setIfExists('items', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param mixed  $defaultValue
     * @param array<string, mixed> $fields
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return float
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param float $id The id of the return
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }

        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets brandId
     *
     * @return int|null
     */
    public function getBrandId()
    {
        return $this->container['brandId'];
    }

    /**
     * Sets brandId
     *
     * @param int|null $brandId brandId
     *
     * @return self
     */
    public function setBrandId($brandId)
    {
        if (is_null($brandId)) {
            throw new \InvalidArgumentException('non-nullable brandId cannot be null');
        }

        $this->container['brandId'] = $brandId;

        return $this;
    }

    /**
     * Gets orderNumber
     *
     * @return string|null
     */
    public function getOrderNumber()
    {
        return $this->container['orderNumber'];
    }

    /**
     * Sets orderNumber
     *
     * @param string|null $orderNumber orderNumber
     *
     * @return self
     */
    public function setOrderNumber($orderNumber)
    {
        if (is_null($orderNumber)) {
            throw new \InvalidArgumentException('non-nullable orderNumber cannot be null');
        }

        $this->container['orderNumber'] = $orderNumber;

        return $this;
    }

    /**
     * Gets returnReasonId
     *
     * @return int|null
     */
    public function getReturnReasonId()
    {
        return $this->container['returnReasonId'];
    }

    /**
     * Sets returnReasonId
     *
     * @param int|null $returnReasonId returnReasonId
     *
     * @return self
     */
    public function setReturnReasonId($returnReasonId)
    {
        if (is_null($returnReasonId)) {
            throw new \InvalidArgumentException('non-nullable returnReasonId cannot be null');
        }

        $this->container['returnReasonId'] = $returnReasonId;

        return $this;
    }

    /**
     * Gets returnAddressId
     *
     * @return int|null
     */
    public function getReturnAddressId()
    {
        return $this->container['returnAddressId'];
    }

    /**
     * Sets returnAddressId
     *
     * @param int|null $returnAddressId returnAddressId
     *
     * @return self
     */
    public function setReturnAddressId($returnAddressId)
    {
        if (is_null($returnAddressId)) {
            throw new \InvalidArgumentException('non-nullable returnAddressId cannot be null');
        }

        $this->container['returnAddressId'] = $returnAddressId;

        return $this;
    }

    /**
     * Gets paidReturn
     *
     * @return bool|null
     */
    public function getPaidReturn()
    {
        return $this->container['paidReturn'];
    }

    /**
     * Sets paidReturn
     *
     * @param bool|null $paidReturn paidReturn
     *
     * @return self
     */
    public function setPaidReturn($paidReturn)
    {
        if (is_null($paidReturn)) {
            throw new \InvalidArgumentException('non-nullable paidReturn cannot be null');
        }

        $this->container['paidReturn'] = $paidReturn;

        return $this;
    }

    /**
     * Gets deliveryChoice
     *
     * @return string|null
     */
    public function getDeliveryChoice()
    {
        return $this->container['deliveryChoice'];
    }

    /**
     * Sets deliveryChoice
     *
     * @param string|null $deliveryChoice deliveryChoice
     *
     * @return self
     */
    public function setDeliveryChoice($deliveryChoice)
    {
        if (is_null($deliveryChoice)) {
            throw new \InvalidArgumentException('non-nullable deliveryChoice cannot be null');
        }

        $this->container['deliveryChoice'] = $deliveryChoice;

        return $this;
    }

    /**
     * Gets refundType
     *
     * @return string|null
     */
    public function getRefundType()
    {
        return $this->container['refundType'];
    }

    /**
     * Sets refundType
     *
     * @param string|null $refundType refundType
     *
     * @return self
     */
    public function setRefundType($refundType)
    {
        if (is_null($refundType)) {
            throw new \InvalidArgumentException('non-nullable refundType cannot be null');
        }

        $this->container['refundType'] = $refundType;

        return $this;
    }

    /**
     * Gets items
     *
     * @return \Toppy\Sendcloud\Model\ReturnCreatedWebhookDataItemsInner[]|null
     */
    public function getItems()
    {
        return $this->container['items'];
    }

    /**
     * Sets items
     *
     * @param \Toppy\Sendcloud\Model\ReturnCreatedWebhookDataItemsInner[]|null $items List of items for this return
     *
     * @return self
     */
    public function setItems($items)
    {
        if (is_null($items)) {
            throw new \InvalidArgumentException('non-nullable items cannot be null');
        }

        $this->container['items'] = $items;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     */
    public function __toString(): string
    {
        return (string) json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
