<?php

declare(strict_types=1);

/**
 * ShipmentCreateUpdateLog
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Toppy\Sendcloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
/**
 * Sendcloud Public REST API
 *
 * Complete Sendcloud API v2 specification - merged from official sendcloud.dev documentation
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@sendcloud.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
namespace Toppy\Sendcloud\Model;

use \ArrayAccess;
use \Toppy\Sendcloud\ObjectSerializer;

/**
 * ShipmentCreateUpdateLog Class Doc Comment
 *
 * @category Class
 * @package  Toppy\Sendcloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ShipmentCreateUpdateLog implements ModelInterface, ArrayAccess, \JsonSerializable, \Stringable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ShipmentCreateUpdateLog';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'externalOrderId' => 'string',
        'externalShipmentId' => 'string',
        'shipmentUuid' => 'string',
        'status' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'externalOrderId' => null,
        'externalShipmentId' => null,
        'shipmentUuid' => 'uuid',
        'status' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'externalOrderId' => false,
        'externalShipmentId' => false,
        'shipmentUuid' => false,
        'status' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Checks if a property is nullable
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->openAPINullablesSetToNull, true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'externalOrderId' => 'external_order_id',
        'externalShipmentId' => 'external_shipment_id',
        'shipmentUuid' => 'shipment_uuid',
        'status' => 'status'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'externalOrderId' => 'setExternalOrderId',
        'externalShipmentId' => 'setExternalShipmentId',
        'shipmentUuid' => 'setShipmentUuid',
        'status' => 'setStatus'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'externalOrderId' => 'getExternalOrderId',
        'externalShipmentId' => 'getExternalShipmentId',
        'shipmentUuid' => 'getShipmentUuid',
        'status' => 'getStatus'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const STATUS_CREATED = 'created';

    public const STATUS_UPDATED = 'updated';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_CREATED,
            self::STATUS_UPDATED,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('externalOrderId', $data ?? [], null);
        $this->setIfExists('externalShipmentId', $data ?? [], null);
        $this->setIfExists('shipmentUuid', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param mixed  $defaultValue
     * @param array<string, mixed> $fields
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['externalOrderId']) && (mb_strlen($this->container['externalOrderId']) < 1)) {
            $invalidProperties[] = "invalid value for 'externalOrderId', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['externalShipmentId']) && (mb_strlen($this->container['externalShipmentId']) < 1)) {
            $invalidProperties[] = "invalid value for 'externalShipmentId', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['shipmentUuid']) && (mb_strlen($this->container['shipmentUuid']) < 1)) {
            $invalidProperties[] = "invalid value for 'shipmentUuid', the character length must be bigger than or equal to 1.";
        }

        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets externalOrderId
     *
     * @return string|null
     */
    public function getExternalOrderId()
    {
        return $this->container['externalOrderId'];
    }

    /**
     * Sets externalOrderId
     *
     * @param string|null $externalOrderId externalOrderId
     *
     * @return self
     */
    public function setExternalOrderId($externalOrderId)
    {
        if (is_null($externalOrderId)) {
            throw new \InvalidArgumentException('non-nullable externalOrderId cannot be null');
        }

        if ((mb_strlen($externalOrderId) < 1)) {
            throw new \InvalidArgumentException('invalid length for $externalOrderId when calling ShipmentCreateUpdateLog., must be bigger than or equal to 1.');
        }

        $this->container['externalOrderId'] = $externalOrderId;

        return $this;
    }

    /**
     * Gets externalShipmentId
     *
     * @return string|null
     */
    public function getExternalShipmentId()
    {
        return $this->container['externalShipmentId'];
    }

    /**
     * Sets externalShipmentId
     *
     * @param string|null $externalShipmentId externalShipmentId
     *
     * @return self
     */
    public function setExternalShipmentId($externalShipmentId)
    {
        if (is_null($externalShipmentId)) {
            throw new \InvalidArgumentException('non-nullable externalShipmentId cannot be null');
        }

        if ((mb_strlen($externalShipmentId) < 1)) {
            throw new \InvalidArgumentException('invalid length for $externalShipmentId when calling ShipmentCreateUpdateLog., must be bigger than or equal to 1.');
        }

        $this->container['externalShipmentId'] = $externalShipmentId;

        return $this;
    }

    /**
     * Gets shipmentUuid
     *
     * @return string|null
     */
    public function getShipmentUuid()
    {
        return $this->container['shipmentUuid'];
    }

    /**
     * Sets shipmentUuid
     *
     * @param string|null $shipmentUuid shipmentUuid
     *
     * @return self
     */
    public function setShipmentUuid($shipmentUuid)
    {
        if (is_null($shipmentUuid)) {
            throw new \InvalidArgumentException('non-nullable shipmentUuid cannot be null');
        }

        if ((mb_strlen($shipmentUuid) < 1)) {
            throw new \InvalidArgumentException('invalid length for $shipmentUuid when calling ShipmentCreateUpdateLog., must be bigger than or equal to 1.');
        }

        $this->container['shipmentUuid'] = $shipmentUuid;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }

        $allowedValues = $this->getStatusAllowableValues();
        if (!in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'status', must be one of '%s'",
                    $status,
                    implode("', '", $allowedValues)
                )
            );
        }

        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     */
    public function __toString(): string
    {
        return (string) json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
