<?php

declare(strict_types=1);

/**
 * ShippingMethod
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Toppy\Sendcloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
/**
 * Sendcloud Public REST API
 *
 * Complete Sendcloud API v2 specification - merged from official sendcloud.dev documentation
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@sendcloud.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
namespace Toppy\Sendcloud\Model;

use \ArrayAccess;
use \Toppy\Sendcloud\ObjectSerializer;

/**
 * ShippingMethod Class Doc Comment
 *
 * @category Class
 * @description A Sendcloud shipping method
 * @package  Toppy\Sendcloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ShippingMethod implements ModelInterface, ArrayAccess, \JsonSerializable, \Stringable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'shipping-method';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'int',
        'name' => 'string',
        'carrier' => 'string',
        'minWeight' => 'string',
        'maxWeight' => 'string',
        'servicePointInput' => 'string',
        'price' => 'int',
        'countries' => '\Toppy\Sendcloud\Model\ShippingMethodCountriesInner[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'int64',
        'name' => null,
        'carrier' => null,
        'minWeight' => null,
        'maxWeight' => null,
        'servicePointInput' => null,
        'price' => 'int64',
        'countries' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'name' => false,
        'carrier' => false,
        'minWeight' => false,
        'maxWeight' => false,
        'servicePointInput' => false,
        'price' => false,
        'countries' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Checks if a property is nullable
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->openAPINullablesSetToNull, true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'carrier' => 'carrier',
        'minWeight' => 'min_weight',
        'maxWeight' => 'max_weight',
        'servicePointInput' => 'service_point_input',
        'price' => 'price',
        'countries' => 'countries'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'carrier' => 'setCarrier',
        'minWeight' => 'setMinWeight',
        'maxWeight' => 'setMaxWeight',
        'servicePointInput' => 'setServicePointInput',
        'price' => 'setPrice',
        'countries' => 'setCountries'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'carrier' => 'getCarrier',
        'minWeight' => 'getMinWeight',
        'maxWeight' => 'getMaxWeight',
        'servicePointInput' => 'getServicePointInput',
        'price' => 'getPrice',
        'countries' => 'getCountries'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const SERVICE_POINT_INPUT_REQUIRED = 'required';

    public const SERVICE_POINT_INPUT_NONE = 'none';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getServicePointInputAllowableValues()
    {
        return [
            self::SERVICE_POINT_INPUT_REQUIRED,
            self::SERVICE_POINT_INPUT_NONE,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('carrier', $data ?? [], null);
        $this->setIfExists('minWeight', $data ?? [], null);
        $this->setIfExists('maxWeight', $data ?? [], null);
        $this->setIfExists('servicePointInput', $data ?? [], null);
        $this->setIfExists('price', $data ?? [], null);
        $this->setIfExists('countries', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param mixed  $defaultValue
     * @param array<string, mixed> $fields
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }

        if (($this->container['id'] < 1)) {
            $invalidProperties[] = "invalid value for 'id', must be bigger than or equal to 1.";
        }

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }

        if ((mb_strlen((string) $this->container['name']) < 1)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['carrier'] === null) {
            $invalidProperties[] = "'carrier' can't be null";
        }

        if ((mb_strlen((string) $this->container['carrier']) < 1)) {
            $invalidProperties[] = "invalid value for 'carrier', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['minWeight'] === null) {
            $invalidProperties[] = "'minWeight' can't be null";
        }

        if ((mb_strlen((string) $this->container['minWeight']) < 5)) {
            $invalidProperties[] = "invalid value for 'minWeight', the character length must be bigger than or equal to 5.";
        }

        if ($this->container['maxWeight'] === null) {
            $invalidProperties[] = "'maxWeight' can't be null";
        }

        if ((mb_strlen((string) $this->container['maxWeight']) < 5)) {
            $invalidProperties[] = "invalid value for 'maxWeight', the character length must be bigger than or equal to 5.";
        }

        if ($this->container['servicePointInput'] === null) {
            $invalidProperties[] = "'servicePointInput' can't be null";
        }

        $allowedValues = $this->getServicePointInputAllowableValues();
        if (!is_null($this->container['servicePointInput']) && !in_array($this->container['servicePointInput'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'servicePointInput', must be one of '%s'",
                $this->container['servicePointInput'],
                implode("', '", $allowedValues)
            );
        }

        if ((mb_strlen((string) $this->container['servicePointInput']) < 1)) {
            $invalidProperties[] = "invalid value for 'servicePointInput', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['price'] === null) {
            $invalidProperties[] = "'price' can't be null";
        }

        if (($this->container['price'] > 0)) {
            $invalidProperties[] = "invalid value for 'price', must be smaller than or equal to 0.";
        }

        if (($this->container['price'] < 0)) {
            $invalidProperties[] = "invalid value for 'price', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id Unique identifier of the shipping method.
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }

        if (($id < 1)) {
            throw new \InvalidArgumentException('invalid value for $id when calling ShippingMethod., must be bigger than or equal to 1.');
        }

        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Name of the shipping method, it should give an idea what the shipping method can be used for.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }

        if ((mb_strlen($name) < 1)) {
            throw new \InvalidArgumentException('invalid length for $name when calling ShippingMethod., must be bigger than or equal to 1.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets carrier
     *
     * @return string
     */
    public function getCarrier()
    {
        return $this->container['carrier'];
    }

    /**
     * Sets carrier
     *
     * @param string $carrier A `carrier_code` which will indicate which carrier provides the shipping method.
     *
     * @return self
     */
    public function setCarrier($carrier)
    {
        if (is_null($carrier)) {
            throw new \InvalidArgumentException('non-nullable carrier cannot be null');
        }

        if ((mb_strlen($carrier) < 1)) {
            throw new \InvalidArgumentException('invalid length for $carrier when calling ShippingMethod., must be bigger than or equal to 1.');
        }

        $this->container['carrier'] = $carrier;

        return $this;
    }

    /**
     * Gets minWeight
     *
     * @return string
     */
    public function getMinWeight()
    {
        return $this->container['minWeight'];
    }

    /**
     * Sets minWeight
     *
     * @param string $minWeight Minimum allowed weight of the parcel for this shipping method.
     *
     * @return self
     */
    public function setMinWeight($minWeight)
    {
        if (is_null($minWeight)) {
            throw new \InvalidArgumentException('non-nullable minWeight cannot be null');
        }

        if ((mb_strlen($minWeight) < 5)) {
            throw new \InvalidArgumentException('invalid length for $minWeight when calling ShippingMethod., must be bigger than or equal to 5.');
        }

        $this->container['minWeight'] = $minWeight;

        return $this;
    }

    /**
     * Gets maxWeight
     *
     * @return string
     */
    public function getMaxWeight()
    {
        return $this->container['maxWeight'];
    }

    /**
     * Sets maxWeight
     *
     * @param string $maxWeight Maximum allowed weight of the parcel for this shipping method.
     *
     * @return self
     */
    public function setMaxWeight($maxWeight)
    {
        if (is_null($maxWeight)) {
            throw new \InvalidArgumentException('non-nullable maxWeight cannot be null');
        }

        if ((mb_strlen($maxWeight) < 5)) {
            throw new \InvalidArgumentException('invalid length for $maxWeight when calling ShippingMethod., must be bigger than or equal to 5.');
        }

        $this->container['maxWeight'] = $maxWeight;

        return $this;
    }

    /**
     * Gets servicePointInput
     *
     * @return string
     */
    public function getServicePointInput()
    {
        return $this->container['servicePointInput'];
    }

    /**
     * Sets servicePointInput
     *
     * @param string $servicePointInput Will be either `required` when the shipping method is meant to ship a parcel to a service point, or `none` when this is not the case.
     *
     * @return self
     */
    public function setServicePointInput($servicePointInput)
    {
        if (is_null($servicePointInput)) {
            throw new \InvalidArgumentException('non-nullable servicePointInput cannot be null');
        }

        $allowedValues = $this->getServicePointInputAllowableValues();
        if (!in_array($servicePointInput, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'servicePointInput', must be one of '%s'",
                    $servicePointInput,
                    implode("', '", $allowedValues)
                )
            );
        }

        if ((mb_strlen($servicePointInput) < 1)) {
            throw new \InvalidArgumentException('invalid length for $servicePointInput when calling ShippingMethod., must be bigger than or equal to 1.');
        }

        $this->container['servicePointInput'] = $servicePointInput;

        return $this;
    }

    /**
     * Gets price
     *
     * @return int
     * @deprecated
     */
    public function getPrice()
    {
        return $this->container['price'];
    }

    /**
     * Sets price
     *
     * @param int $price A legacy property which will always be `0`, should not be used!
     *
     * @return self
     * @deprecated
     */
    public function setPrice($price)
    {
        if (is_null($price)) {
            throw new \InvalidArgumentException('non-nullable price cannot be null');
        }

        if (($price > 0)) {
            throw new \InvalidArgumentException('invalid value for $price when calling ShippingMethod., must be smaller than or equal to 0.');
        }

        if (($price < 0)) {
            throw new \InvalidArgumentException('invalid value for $price when calling ShippingMethod., must be bigger than or equal to 0.');
        }

        $this->container['price'] = $price;

        return $this;
    }

    /**
     * Gets countries
     *
     * @return \Toppy\Sendcloud\Model\ShippingMethodCountriesInner[]|null
     */
    public function getCountries()
    {
        return $this->container['countries'];
    }

    /**
     * Sets countries
     *
     * @param \Toppy\Sendcloud\Model\ShippingMethodCountriesInner[]|null $countries A list of countries that you can ship to with the shipping method.
     *
     * @return self
     */
    public function setCountries($countries)
    {
        if (is_null($countries)) {
            throw new \InvalidArgumentException('non-nullable countries cannot be null');
        }

        $this->container['countries'] = $countries;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     */
    public function __toString(): string
    {
        return (string) json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
