<?php

declare(strict_types=1);

/**
 * IntegrationsApi
 * PHP version 7.2
 *
 * @category Class
 * @package  Toppy\Sendcloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
/**
 * Sendcloud Public REST API
 *
 * Complete Sendcloud API v2 specification - merged from official Stoplight documentation bundles
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendcloud.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
namespace Toppy\Sendcloud\Api;

use GuzzleHttp\Psr7\MultipartStream;
use Http\Client\Common\Plugin\ErrorPlugin;
use Http\Client\Common\Plugin\RedirectPlugin;
use Http\Client\Common\PluginClient;
use Http\Client\Common\PluginClientFactory;
use Http\Client\Exception\HttpException;
use Http\Client\HttpAsyncClient;
use Http\Discovery\HttpAsyncClientDiscovery;
use Http\Discovery\Psr17FactoryDiscovery;
use Http\Discovery\Psr18ClientDiscovery;
use Http\Message\RequestFactory;
use Http\Promise\Promise;
use Toppy\Sendcloud\ApiException;
use Toppy\Sendcloud\Configuration;
use Toppy\Sendcloud\DebugPlugin;
use Toppy\Sendcloud\HeaderSelector;
use Toppy\Sendcloud\FormDataProcessor;
use Toppy\Sendcloud\ObjectSerializer;
use Psr\Http\Client\ClientExceptionInterface;
use Psr\Http\Client\ClientInterface;
use Psr\Http\Message\RequestFactoryInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\StreamFactoryInterface;
use Psr\Http\Message\UriFactoryInterface;
use Psr\Http\Message\UriInterface;
use function sprintf;

/**
 * IntegrationsApi Class Doc Comment
 *
 * @category Class
 * @package  Toppy\Sendcloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class IntegrationsApi
{
    /**
     * @var PluginClient
     */
    protected $httpClient;

    /**
     * @var PluginClient
     */
    protected $httpAsyncClient;

    /**
     * @var UriFactoryInterface
     */
    protected $uriFactory;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var RequestFactoryInterface
     */
    protected $requestFactory;

    /**
     * @var StreamFactoryInterface
     */
    protected $streamFactory;

    /**
     * @param int $hostIndex
     */
    public function __construct(
        ?ClientInterface $httpClient = null,
        ?Configuration $configuration = null,
        ?HttpAsyncClient $httpAsyncClient = null,
        ?UriFactoryInterface $uriFactory = null,
        ?RequestFactoryInterface $requestFactory = null,
        ?StreamFactoryInterface $streamFactory = null,
        protected ?HeaderSelector $headerSelector = new HeaderSelector(),
        ?array $plugins = null,
        /**
         * @var int Host index
         */
        protected $hostIndex = 0
    ) {
        $this->config = $configuration ?? (new Configuration())->setHost('https://account.sendcloud.com');
        $this->requestFactory = $requestFactory ?? Psr17FactoryDiscovery::findRequestFactory();
        $this->streamFactory = $streamFactory ?? Psr17FactoryDiscovery::findStreamFactory();

        $plugins = $plugins ?? [
            new RedirectPlugin(['strict' => true]),
            new ErrorPlugin(),
        ];

        if ($this->config->getDebug()) {
            $plugins[] = new DebugPlugin(fopen($this->config->getDebugFile(), 'ab'));
        }

        $this->httpClient = (new PluginClientFactory())->createClient(
            $httpClient ?? Psr18ClientDiscovery::find(),
            $plugins
        );

        $this->httpAsyncClient = (new PluginClientFactory())->createClient(
            $httpAsyncClient ?? HttpAsyncClientDiscovery::find(),
            $plugins
        );

        $this->uriFactory = $uriFactory ?? Psr17FactoryDiscovery::findUriFactory();
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation scPublicV2OrdersDeleteDeleteAnIntegration
     *
     * Delete an integration
     *
     * @param  int $id An id of the integration (required)
     *
     * @throws \Toppy\Sendcloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function scPublicV2OrdersDeleteDeleteAnIntegration($id)
    {
        $this->scPublicV2OrdersDeleteDeleteAnIntegrationWithHttpInfo($id);
    }

    /**
     * Operation scPublicV2OrdersDeleteDeleteAnIntegrationWithHttpInfo
     *
     * Delete an integration
     *
     * @param  int $id An id of the integration (required)
     *
     * @throws \Toppy\Sendcloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array<int, int|string[][]|null> of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function scPublicV2OrdersDeleteDeleteAnIntegrationWithHttpInfo($id)
    {
        $request = $this->scPublicV2OrdersDeleteDeleteAnIntegrationRequest($id);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $apiException) {
            if ($apiException->getCode() === 404) {
                $data = ObjectSerializer::deserialize(
                    $apiException->getResponseBody(),
                    \Toppy\Sendcloud\Model\ScPublicV2OrdersGetRetrieveAnIntegration404Response::class,
                    $apiException->getResponseHeaders()
                );
                $apiException->setResponseObject($data);
                throw $apiException;
            }
        

            throw $apiException;
        }
    }

    /**
     * Operation scPublicV2OrdersDeleteDeleteAnIntegrationAsync
     *
     * Delete an integration
     *
     * @param  int $id An id of the integration (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV2OrdersDeleteDeleteAnIntegrationAsync($id)
    {
        return $this->scPublicV2OrdersDeleteDeleteAnIntegrationAsyncWithHttpInfo($id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation scPublicV2OrdersDeleteDeleteAnIntegrationAsyncWithHttpInfo
     *
     * Delete an integration
     *
     * @param  int $id An id of the integration (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV2OrdersDeleteDeleteAnIntegrationAsyncWithHttpInfo($id)
    {
        $request = $this->scPublicV2OrdersDeleteDeleteAnIntegrationRequest($id);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function (HttpException $httpException) {
                    $response = $httpException->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $httpException->getRequest()->getUri()
                        ),
                        $httpException->getRequest(),
                        $httpException->getResponse(),
                        $httpException
                    );
                }
            );
    }

    /**
     * Create request for operation 'scPublicV2OrdersDeleteDeleteAnIntegration'
     *
     * @param  int $id An id of the integration (required)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function scPublicV2OrdersDeleteDeleteAnIntegrationRequest($id)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && $id === [])) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling scPublicV2OrdersDeleteDeleteAnIntegration'
            );
        }

        $resourcePath = '/integrations/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;



        // path params
        $resourcePath = str_replace(
            '{id}',
            ObjectSerializer::toPathValue($id),
            $resourcePath
        );


        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('DELETE', $uri, $headers, $httpBody);
    }

    /**
     * Operation scPublicV2OrdersGetRetrieveAListOfIntegrations
     *
     * Retrieve a list of integrations
     *
     * @param  string $ordering Specifies the field used to order the resulting response (optional)
     *
     * @throws \Toppy\Sendcloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Toppy\Sendcloud\Model\Integration[]
     */
    public function scPublicV2OrdersGetRetrieveAListOfIntegrations($ordering = null)
    {
        [$response] = $this->scPublicV2OrdersGetRetrieveAListOfIntegrationsWithHttpInfo($ordering);
        return $response;
    }

    /**
     * Operation scPublicV2OrdersGetRetrieveAListOfIntegrationsWithHttpInfo
     *
     * Retrieve a list of integrations
     *
     * @param  string $ordering Specifies the field used to order the resulting response (optional)
     *
     * @throws \Toppy\Sendcloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Toppy\Sendcloud\Model\Integration[], HTTP status code, HTTP response headers (array of strings)
     */
    public function scPublicV2OrdersGetRetrieveAListOfIntegrationsWithHttpInfo($ordering = null)
    {
        $request = $this->scPublicV2OrdersGetRetrieveAListOfIntegrationsRequest($ordering);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            if ($statusCode === 200) {
                return $this->handleResponseWithDataType(
                    '\Toppy\Sendcloud\Model\Integration[]',
                    $request,
                    $response,
                );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $request,
                    $response
                );
            }

            return $this->handleResponseWithDataType(
                '\Toppy\Sendcloud\Model\Integration[]',
                $request,
                $response,
            );
        } catch (ApiException $apiException) {
            if ($apiException->getCode() === 200) {
                $data = ObjectSerializer::deserialize(
                    $apiException->getResponseBody(),
                    '\Toppy\Sendcloud\Model\Integration[]',
                    $apiException->getResponseHeaders()
                );
                $apiException->setResponseObject($data);
                throw $apiException;
            }
        

            throw $apiException;
        }
    }

    /**
     * Operation scPublicV2OrdersGetRetrieveAListOfIntegrationsAsync
     *
     * Retrieve a list of integrations
     *
     * @param  string $ordering Specifies the field used to order the resulting response (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV2OrdersGetRetrieveAListOfIntegrationsAsync($ordering = null)
    {
        return $this->scPublicV2OrdersGetRetrieveAListOfIntegrationsAsyncWithHttpInfo($ordering)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation scPublicV2OrdersGetRetrieveAListOfIntegrationsAsyncWithHttpInfo
     *
     * Retrieve a list of integrations
     *
     * @param  string $ordering Specifies the field used to order the resulting response (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV2OrdersGetRetrieveAListOfIntegrationsAsyncWithHttpInfo($ordering = null)
    {
        $returnType = '\Toppy\Sendcloud\Model\Integration[]';
        $request = $this->scPublicV2OrdersGetRetrieveAListOfIntegrationsRequest($ordering);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $httpException) {
                    $response = $httpException->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $httpException->getRequest()->getUri()
                        ),
                        $httpException->getRequest(),
                        $httpException->getResponse(),
                        $httpException
                    );
                }
            );
    }

    /**
     * Create request for operation 'scPublicV2OrdersGetRetrieveAListOfIntegrations'
     *
     * @param  string $ordering Specifies the field used to order the resulting response (optional)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function scPublicV2OrdersGetRetrieveAListOfIntegrationsRequest($ordering = null)
    {

        $resourcePath = '/integrations';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // query params
        if ($ordering !== null) {
            if(is_array($ordering)) {
                foreach($ordering as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['ordering'] = $ordering;
            }
        }




        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }

    /**
     * Operation scPublicV2OrdersGetRetrieveAnIntegration
     *
     * Retrieve an integration
     *
     * @param  int $id An id of the integration (required)
     *
     * @throws \Toppy\Sendcloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Toppy\Sendcloud\Model\Integration|\Toppy\Sendcloud\Model\ScPublicV2OrdersGetRetrieveAnIntegration404Response
     */
    public function scPublicV2OrdersGetRetrieveAnIntegration($id)
    {
        [$response] = $this->scPublicV2OrdersGetRetrieveAnIntegrationWithHttpInfo($id);
        return $response;
    }

    /**
     * Operation scPublicV2OrdersGetRetrieveAnIntegrationWithHttpInfo
     *
     * Retrieve an integration
     *
     * @param  int $id An id of the integration (required)
     *
     * @throws \Toppy\Sendcloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Toppy\Sendcloud\Model\Integration|\Toppy\Sendcloud\Model\ScPublicV2OrdersGetRetrieveAnIntegration404Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function scPublicV2OrdersGetRetrieveAnIntegrationWithHttpInfo($id)
    {
        $request = $this->scPublicV2OrdersGetRetrieveAnIntegrationRequest($id);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        \Toppy\Sendcloud\Model\Integration::class,
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        \Toppy\Sendcloud\Model\ScPublicV2OrdersGetRetrieveAnIntegration404Response::class,
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $request,
                    $response
                );
            }

            return $this->handleResponseWithDataType(
                \Toppy\Sendcloud\Model\Integration::class,
                $request,
                $response,
            );
        } catch (ApiException $apiException) {
            switch ($apiException->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        \Toppy\Sendcloud\Model\Integration::class,
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);
                    throw $apiException;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        \Toppy\Sendcloud\Model\ScPublicV2OrdersGetRetrieveAnIntegration404Response::class,
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);
                    throw $apiException;
            }
        

            throw $apiException;
        }
    }

    /**
     * Operation scPublicV2OrdersGetRetrieveAnIntegrationAsync
     *
     * Retrieve an integration
     *
     * @param  int $id An id of the integration (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV2OrdersGetRetrieveAnIntegrationAsync($id)
    {
        return $this->scPublicV2OrdersGetRetrieveAnIntegrationAsyncWithHttpInfo($id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation scPublicV2OrdersGetRetrieveAnIntegrationAsyncWithHttpInfo
     *
     * Retrieve an integration
     *
     * @param  int $id An id of the integration (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV2OrdersGetRetrieveAnIntegrationAsyncWithHttpInfo($id)
    {
        $returnType = \Toppy\Sendcloud\Model\Integration::class;
        $request = $this->scPublicV2OrdersGetRetrieveAnIntegrationRequest($id);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $httpException) {
                    $response = $httpException->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $httpException->getRequest()->getUri()
                        ),
                        $httpException->getRequest(),
                        $httpException->getResponse(),
                        $httpException
                    );
                }
            );
    }

    /**
     * Create request for operation 'scPublicV2OrdersGetRetrieveAnIntegration'
     *
     * @param  int $id An id of the integration (required)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function scPublicV2OrdersGetRetrieveAnIntegrationRequest($id)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && $id === [])) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling scPublicV2OrdersGetRetrieveAnIntegration'
            );
        }

        $resourcePath = '/integrations/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;



        // path params
        $resourcePath = str_replace(
            '{id}',
            ObjectSerializer::toPathValue($id),
            $resourcePath
        );


        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }

    /**
     * Operation scPublicV2OrdersGetRetrieveIntegrationLogs
     *
     * Retrieve integration exceptions logs
     *
     * @param  int $id An id of an integration to which the shipments belong (required)
     *
     * @throws \Toppy\Sendcloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Toppy\Sendcloud\Model\ScPublicV2OrdersGetRetrieveIntegrationsLogs200Response|\Toppy\Sendcloud\Model\ScPublicV2OrdersGetRetrieveAnIntegration404Response
     */
    public function scPublicV2OrdersGetRetrieveIntegrationLogs($id)
    {
        [$response] = $this->scPublicV2OrdersGetRetrieveIntegrationLogsWithHttpInfo($id);
        return $response;
    }

    /**
     * Operation scPublicV2OrdersGetRetrieveIntegrationLogsWithHttpInfo
     *
     * Retrieve integration exceptions logs
     *
     * @param  int $id An id of an integration to which the shipments belong (required)
     *
     * @throws \Toppy\Sendcloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Toppy\Sendcloud\Model\ScPublicV2OrdersGetRetrieveIntegrationsLogs200Response|\Toppy\Sendcloud\Model\ScPublicV2OrdersGetRetrieveAnIntegration404Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function scPublicV2OrdersGetRetrieveIntegrationLogsWithHttpInfo($id)
    {
        $request = $this->scPublicV2OrdersGetRetrieveIntegrationLogsRequest($id);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        \Toppy\Sendcloud\Model\ScPublicV2OrdersGetRetrieveIntegrationsLogs200Response::class,
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        \Toppy\Sendcloud\Model\ScPublicV2OrdersGetRetrieveAnIntegration404Response::class,
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $request,
                    $response
                );
            }

            return $this->handleResponseWithDataType(
                \Toppy\Sendcloud\Model\ScPublicV2OrdersGetRetrieveIntegrationsLogs200Response::class,
                $request,
                $response,
            );
        } catch (ApiException $apiException) {
            switch ($apiException->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        \Toppy\Sendcloud\Model\ScPublicV2OrdersGetRetrieveIntegrationsLogs200Response::class,
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);
                    throw $apiException;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        \Toppy\Sendcloud\Model\ScPublicV2OrdersGetRetrieveAnIntegration404Response::class,
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);
                    throw $apiException;
            }
        

            throw $apiException;
        }
    }

    /**
     * Operation scPublicV2OrdersGetRetrieveIntegrationLogsAsync
     *
     * Retrieve integration exceptions logs
     *
     * @param  int $id An id of an integration to which the shipments belong (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV2OrdersGetRetrieveIntegrationLogsAsync($id)
    {
        return $this->scPublicV2OrdersGetRetrieveIntegrationLogsAsyncWithHttpInfo($id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation scPublicV2OrdersGetRetrieveIntegrationLogsAsyncWithHttpInfo
     *
     * Retrieve integration exceptions logs
     *
     * @param  int $id An id of an integration to which the shipments belong (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV2OrdersGetRetrieveIntegrationLogsAsyncWithHttpInfo($id)
    {
        $returnType = \Toppy\Sendcloud\Model\ScPublicV2OrdersGetRetrieveIntegrationsLogs200Response::class;
        $request = $this->scPublicV2OrdersGetRetrieveIntegrationLogsRequest($id);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $httpException) {
                    $response = $httpException->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $httpException->getRequest()->getUri()
                        ),
                        $httpException->getRequest(),
                        $httpException->getResponse(),
                        $httpException
                    );
                }
            );
    }

    /**
     * Create request for operation 'scPublicV2OrdersGetRetrieveIntegrationLogs'
     *
     * @param  int $id An id of an integration to which the shipments belong (required)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function scPublicV2OrdersGetRetrieveIntegrationLogsRequest($id)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && $id === [])) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling scPublicV2OrdersGetRetrieveIntegrationLogs'
            );
        }

        $resourcePath = '/integrations/{id}/logs';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;



        // path params
        $resourcePath = str_replace(
            '{id}',
            ObjectSerializer::toPathValue($id),
            $resourcePath
        );


        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }

    /**
     * Operation scPublicV2OrdersGetRetrieveIntegrationsLogs
     *
     * Retrieve all integration exceptions logs
     *
     *
     * @throws \Toppy\Sendcloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Toppy\Sendcloud\Model\ScPublicV2OrdersGetRetrieveIntegrationsLogs200Response
     */
    public function scPublicV2OrdersGetRetrieveIntegrationsLogs()
    {
        [$response] = $this->scPublicV2OrdersGetRetrieveIntegrationsLogsWithHttpInfo();
        return $response;
    }

    /**
     * Operation scPublicV2OrdersGetRetrieveIntegrationsLogsWithHttpInfo
     *
     * Retrieve all integration exceptions logs
     *
     *
     * @throws \Toppy\Sendcloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Toppy\Sendcloud\Model\ScPublicV2OrdersGetRetrieveIntegrationsLogs200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function scPublicV2OrdersGetRetrieveIntegrationsLogsWithHttpInfo()
    {
        $request = $this->scPublicV2OrdersGetRetrieveIntegrationsLogsRequest();

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            if ($statusCode === 200) {
                return $this->handleResponseWithDataType(
                    \Toppy\Sendcloud\Model\ScPublicV2OrdersGetRetrieveIntegrationsLogs200Response::class,
                    $request,
                    $response,
                );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $request,
                    $response
                );
            }

            return $this->handleResponseWithDataType(
                \Toppy\Sendcloud\Model\ScPublicV2OrdersGetRetrieveIntegrationsLogs200Response::class,
                $request,
                $response,
            );
        } catch (ApiException $apiException) {
            if ($apiException->getCode() === 200) {
                $data = ObjectSerializer::deserialize(
                    $apiException->getResponseBody(),
                    \Toppy\Sendcloud\Model\ScPublicV2OrdersGetRetrieveIntegrationsLogs200Response::class,
                    $apiException->getResponseHeaders()
                );
                $apiException->setResponseObject($data);
                throw $apiException;
            }
        

            throw $apiException;
        }
    }

    /**
     * Operation scPublicV2OrdersGetRetrieveIntegrationsLogsAsync
     *
     * Retrieve all integration exceptions logs
     *
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV2OrdersGetRetrieveIntegrationsLogsAsync()
    {
        return $this->scPublicV2OrdersGetRetrieveIntegrationsLogsAsyncWithHttpInfo()
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation scPublicV2OrdersGetRetrieveIntegrationsLogsAsyncWithHttpInfo
     *
     * Retrieve all integration exceptions logs
     *
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV2OrdersGetRetrieveIntegrationsLogsAsyncWithHttpInfo()
    {
        $returnType = \Toppy\Sendcloud\Model\ScPublicV2OrdersGetRetrieveIntegrationsLogs200Response::class;
        $request = $this->scPublicV2OrdersGetRetrieveIntegrationsLogsRequest();

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $httpException) {
                    $response = $httpException->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $httpException->getRequest()->getUri()
                        ),
                        $httpException->getRequest(),
                        $httpException->getResponse(),
                        $httpException
                    );
                }
            );
    }

    /**
     * Create request for operation 'scPublicV2OrdersGetRetrieveIntegrationsLogs'
     *
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function scPublicV2OrdersGetRetrieveIntegrationsLogsRequest()
    {

        $resourcePath = '/integrations/logs';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }

    /**
     * Operation scPublicV2OrdersPatchPartialUpdateAnIntegration
     *
     * Update an integration
     *
     * @param  int $id An id of the integration (required)
     * @param  \Toppy\Sendcloud\Model\IntegrationUpdate $integrationUpdate integrationUpdate (optional)
     *
     * @throws \Toppy\Sendcloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Toppy\Sendcloud\Model\IntegrationUpdate|\Toppy\Sendcloud\Model\ScPublicV2OrdersPutUpdateAnIntegration400Response|\Toppy\Sendcloud\Model\ScPublicV2OrdersGetRetrieveAnIntegration404Response
     */
    public function scPublicV2OrdersPatchPartialUpdateAnIntegration($id, $integrationUpdate = null)
    {
        [$response] = $this->scPublicV2OrdersPatchPartialUpdateAnIntegrationWithHttpInfo($id, $integrationUpdate);
        return $response;
    }

    /**
     * Operation scPublicV2OrdersPatchPartialUpdateAnIntegrationWithHttpInfo
     *
     * Update an integration
     *
     * @param  int $id An id of the integration (required)
     * @param  \Toppy\Sendcloud\Model\IntegrationUpdate $integrationUpdate (optional)
     *
     * @throws \Toppy\Sendcloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Toppy\Sendcloud\Model\IntegrationUpdate|\Toppy\Sendcloud\Model\ScPublicV2OrdersPutUpdateAnIntegration400Response|\Toppy\Sendcloud\Model\ScPublicV2OrdersGetRetrieveAnIntegration404Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function scPublicV2OrdersPatchPartialUpdateAnIntegrationWithHttpInfo($id, $integrationUpdate = null)
    {
        $request = $this->scPublicV2OrdersPatchPartialUpdateAnIntegrationRequest($id, $integrationUpdate);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        \Toppy\Sendcloud\Model\IntegrationUpdate::class,
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        \Toppy\Sendcloud\Model\ScPublicV2OrdersPutUpdateAnIntegration400Response::class,
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        \Toppy\Sendcloud\Model\ScPublicV2OrdersGetRetrieveAnIntegration404Response::class,
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $request,
                    $response
                );
            }

            return $this->handleResponseWithDataType(
                \Toppy\Sendcloud\Model\IntegrationUpdate::class,
                $request,
                $response,
            );
        } catch (ApiException $apiException) {
            switch ($apiException->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        \Toppy\Sendcloud\Model\IntegrationUpdate::class,
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);
                    throw $apiException;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        \Toppy\Sendcloud\Model\ScPublicV2OrdersPutUpdateAnIntegration400Response::class,
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);
                    throw $apiException;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        \Toppy\Sendcloud\Model\ScPublicV2OrdersGetRetrieveAnIntegration404Response::class,
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);
                    throw $apiException;
            }
        

            throw $apiException;
        }
    }

    /**
     * Operation scPublicV2OrdersPatchPartialUpdateAnIntegrationAsync
     *
     * Update an integration
     *
     * @param  int $id An id of the integration (required)
     * @param  \Toppy\Sendcloud\Model\IntegrationUpdate $integrationUpdate (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV2OrdersPatchPartialUpdateAnIntegrationAsync($id, $integrationUpdate = null)
    {
        return $this->scPublicV2OrdersPatchPartialUpdateAnIntegrationAsyncWithHttpInfo($id, $integrationUpdate)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation scPublicV2OrdersPatchPartialUpdateAnIntegrationAsyncWithHttpInfo
     *
     * Update an integration
     *
     * @param  int $id An id of the integration (required)
     * @param  \Toppy\Sendcloud\Model\IntegrationUpdate $integrationUpdate (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV2OrdersPatchPartialUpdateAnIntegrationAsyncWithHttpInfo($id, $integrationUpdate = null)
    {
        $returnType = \Toppy\Sendcloud\Model\IntegrationUpdate::class;
        $request = $this->scPublicV2OrdersPatchPartialUpdateAnIntegrationRequest($id, $integrationUpdate);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $httpException) {
                    $response = $httpException->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $httpException->getRequest()->getUri()
                        ),
                        $httpException->getRequest(),
                        $httpException->getResponse(),
                        $httpException
                    );
                }
            );
    }

    /**
     * Create request for operation 'scPublicV2OrdersPatchPartialUpdateAnIntegration'
     *
     * @param  int $id An id of the integration (required)
     * @param  \Toppy\Sendcloud\Model\IntegrationUpdate $integrationUpdate (optional)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function scPublicV2OrdersPatchPartialUpdateAnIntegrationRequest($id, $integrationUpdate = null)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && $id === [])) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling scPublicV2OrdersPatchPartialUpdateAnIntegration'
            );
        }

        $resourcePath = '/integrations/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;



        // path params
        $resourcePath = str_replace(
            '{id}',
            ObjectSerializer::toPathValue($id),
            $resourcePath
        );


        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            'application/json',
            $multipart
        );

        // for model (json/xml)
        if (isset($integrationUpdate)) {
            if ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($integrationUpdate));
            } else {
                $httpBody = $integrationUpdate;
            }
        } elseif ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('PATCH', $uri, $headers, $httpBody);
    }

    /**
     * Operation scPublicV2OrdersPostCreateIntegrationLogs
     *
     * Create integration exceptions logs
     *
     * @param  int $id An id of an integration to which the shipments belong (required)
     * @param  \Toppy\Sendcloud\Model\IntegrationLog $integrationLog integrationLog (optional)
     *
     * @throws \Toppy\Sendcloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Toppy\Sendcloud\Model\IntegrationLog|\Toppy\Sendcloud\Model\ScPublicV2OrdersPutUpdateAnIntegration400Response|\Toppy\Sendcloud\Model\ScPublicV2OrdersGetRetrieveAnIntegration404Response
     */
    public function scPublicV2OrdersPostCreateIntegrationLogs($id, $integrationLog = null)
    {
        [$response] = $this->scPublicV2OrdersPostCreateIntegrationLogsWithHttpInfo($id, $integrationLog);
        return $response;
    }

    /**
     * Operation scPublicV2OrdersPostCreateIntegrationLogsWithHttpInfo
     *
     * Create integration exceptions logs
     *
     * @param  int $id An id of an integration to which the shipments belong (required)
     * @param  \Toppy\Sendcloud\Model\IntegrationLog $integrationLog (optional)
     *
     * @throws \Toppy\Sendcloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Toppy\Sendcloud\Model\IntegrationLog|\Toppy\Sendcloud\Model\ScPublicV2OrdersPutUpdateAnIntegration400Response|\Toppy\Sendcloud\Model\ScPublicV2OrdersGetRetrieveAnIntegration404Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function scPublicV2OrdersPostCreateIntegrationLogsWithHttpInfo($id, $integrationLog = null)
    {
        $request = $this->scPublicV2OrdersPostCreateIntegrationLogsRequest($id, $integrationLog);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    return $this->handleResponseWithDataType(
                        \Toppy\Sendcloud\Model\IntegrationLog::class,
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        \Toppy\Sendcloud\Model\ScPublicV2OrdersPutUpdateAnIntegration400Response::class,
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        \Toppy\Sendcloud\Model\ScPublicV2OrdersGetRetrieveAnIntegration404Response::class,
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $request,
                    $response
                );
            }

            return $this->handleResponseWithDataType(
                \Toppy\Sendcloud\Model\IntegrationLog::class,
                $request,
                $response,
            );
        } catch (ApiException $apiException) {
            switch ($apiException->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        \Toppy\Sendcloud\Model\IntegrationLog::class,
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);
                    throw $apiException;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        \Toppy\Sendcloud\Model\ScPublicV2OrdersPutUpdateAnIntegration400Response::class,
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);
                    throw $apiException;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        \Toppy\Sendcloud\Model\ScPublicV2OrdersGetRetrieveAnIntegration404Response::class,
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);
                    throw $apiException;
            }
        

            throw $apiException;
        }
    }

    /**
     * Operation scPublicV2OrdersPostCreateIntegrationLogsAsync
     *
     * Create integration exceptions logs
     *
     * @param  int $id An id of an integration to which the shipments belong (required)
     * @param  \Toppy\Sendcloud\Model\IntegrationLog $integrationLog (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV2OrdersPostCreateIntegrationLogsAsync($id, $integrationLog = null)
    {
        return $this->scPublicV2OrdersPostCreateIntegrationLogsAsyncWithHttpInfo($id, $integrationLog)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation scPublicV2OrdersPostCreateIntegrationLogsAsyncWithHttpInfo
     *
     * Create integration exceptions logs
     *
     * @param  int $id An id of an integration to which the shipments belong (required)
     * @param  \Toppy\Sendcloud\Model\IntegrationLog $integrationLog (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV2OrdersPostCreateIntegrationLogsAsyncWithHttpInfo($id, $integrationLog = null)
    {
        $returnType = \Toppy\Sendcloud\Model\IntegrationLog::class;
        $request = $this->scPublicV2OrdersPostCreateIntegrationLogsRequest($id, $integrationLog);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $httpException) {
                    $response = $httpException->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $httpException->getRequest()->getUri()
                        ),
                        $httpException->getRequest(),
                        $httpException->getResponse(),
                        $httpException
                    );
                }
            );
    }

    /**
     * Create request for operation 'scPublicV2OrdersPostCreateIntegrationLogs'
     *
     * @param  int $id An id of an integration to which the shipments belong (required)
     * @param  \Toppy\Sendcloud\Model\IntegrationLog $integrationLog (optional)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function scPublicV2OrdersPostCreateIntegrationLogsRequest($id, $integrationLog = null)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && $id === [])) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling scPublicV2OrdersPostCreateIntegrationLogs'
            );
        }

        $resourcePath = '/integrations/{id}/logs';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;



        // path params
        $resourcePath = str_replace(
            '{id}',
            ObjectSerializer::toPathValue($id),
            $resourcePath
        );


        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            'application/json',
            $multipart
        );

        // for model (json/xml)
        if (isset($integrationLog)) {
            if ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($integrationLog));
            } else {
                $httpBody = $integrationLog;
            }
        } elseif ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('POST', $uri, $headers, $httpBody);
    }

    /**
     * Operation scPublicV2OrdersPutUpdateAnIntegration
     *
     * Update an integration
     *
     * @param  int $id An id of the integration (required)
     * @param  \Toppy\Sendcloud\Model\IntegrationUpdate $integrationUpdate  (optional)
     *
     * @throws \Toppy\Sendcloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Toppy\Sendcloud\Model\IntegrationUpdate|\Toppy\Sendcloud\Model\ScPublicV2OrdersPutUpdateAnIntegration400Response|\Toppy\Sendcloud\Model\ScPublicV2OrdersGetRetrieveAnIntegration404Response
     */
    public function scPublicV2OrdersPutUpdateAnIntegration($id, $integrationUpdate = null)
    {
        [$response] = $this->scPublicV2OrdersPutUpdateAnIntegrationWithHttpInfo($id, $integrationUpdate);
        return $response;
    }

    /**
     * Operation scPublicV2OrdersPutUpdateAnIntegrationWithHttpInfo
     *
     * Update an integration
     *
     * @param  int $id An id of the integration (required)
     * @param  \Toppy\Sendcloud\Model\IntegrationUpdate $integrationUpdate  (optional)
     *
     * @throws \Toppy\Sendcloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Toppy\Sendcloud\Model\IntegrationUpdate|\Toppy\Sendcloud\Model\ScPublicV2OrdersPutUpdateAnIntegration400Response|\Toppy\Sendcloud\Model\ScPublicV2OrdersGetRetrieveAnIntegration404Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function scPublicV2OrdersPutUpdateAnIntegrationWithHttpInfo($id, $integrationUpdate = null)
    {
        $request = $this->scPublicV2OrdersPutUpdateAnIntegrationRequest($id, $integrationUpdate);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        \Toppy\Sendcloud\Model\IntegrationUpdate::class,
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        \Toppy\Sendcloud\Model\ScPublicV2OrdersPutUpdateAnIntegration400Response::class,
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        \Toppy\Sendcloud\Model\ScPublicV2OrdersGetRetrieveAnIntegration404Response::class,
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $request,
                    $response
                );
            }

            return $this->handleResponseWithDataType(
                \Toppy\Sendcloud\Model\IntegrationUpdate::class,
                $request,
                $response,
            );
        } catch (ApiException $apiException) {
            switch ($apiException->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        \Toppy\Sendcloud\Model\IntegrationUpdate::class,
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);
                    throw $apiException;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        \Toppy\Sendcloud\Model\ScPublicV2OrdersPutUpdateAnIntegration400Response::class,
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);
                    throw $apiException;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        \Toppy\Sendcloud\Model\ScPublicV2OrdersGetRetrieveAnIntegration404Response::class,
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);
                    throw $apiException;
            }
        

            throw $apiException;
        }
    }

    /**
     * Operation scPublicV2OrdersPutUpdateAnIntegrationAsync
     *
     * Update an integration
     *
     * @param  int $id An id of the integration (required)
     * @param  \Toppy\Sendcloud\Model\IntegrationUpdate $integrationUpdate  (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV2OrdersPutUpdateAnIntegrationAsync($id, $integrationUpdate = null)
    {
        return $this->scPublicV2OrdersPutUpdateAnIntegrationAsyncWithHttpInfo($id, $integrationUpdate)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation scPublicV2OrdersPutUpdateAnIntegrationAsyncWithHttpInfo
     *
     * Update an integration
     *
     * @param  int $id An id of the integration (required)
     * @param  \Toppy\Sendcloud\Model\IntegrationUpdate $integrationUpdate  (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV2OrdersPutUpdateAnIntegrationAsyncWithHttpInfo($id, $integrationUpdate = null)
    {
        $returnType = \Toppy\Sendcloud\Model\IntegrationUpdate::class;
        $request = $this->scPublicV2OrdersPutUpdateAnIntegrationRequest($id, $integrationUpdate);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $httpException) {
                    $response = $httpException->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $httpException->getRequest()->getUri()
                        ),
                        $httpException->getRequest(),
                        $httpException->getResponse(),
                        $httpException
                    );
                }
            );
    }

    /**
     * Create request for operation 'scPublicV2OrdersPutUpdateAnIntegration'
     *
     * @param  int $id An id of the integration (required)
     * @param  \Toppy\Sendcloud\Model\IntegrationUpdate $integrationUpdate  (optional)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function scPublicV2OrdersPutUpdateAnIntegrationRequest($id, $integrationUpdate = null)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && $id === [])) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling scPublicV2OrdersPutUpdateAnIntegration'
            );
        }

        $resourcePath = '/integrations/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;



        // path params
        $resourcePath = str_replace(
            '{id}',
            ObjectSerializer::toPathValue($id),
            $resourcePath
        );


        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            'application/json',
            $multipart
        );

        // for model (json/xml)
        if (isset($integrationUpdate)) {
            if ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($integrationUpdate));
            } else {
                $httpBody = $integrationUpdate;
            }
        } elseif ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('PUT', $uri, $headers, $httpBody);
    }


    /**
     * @param string|UriInterface $uri
     * @param string[] $headers
     * @param string|StreamInterface|null $body
     *
     */
    protected function createRequest(string $method, $uri, array $headers = [], $body = null): RequestInterface
    {
        if ($this->requestFactory instanceof RequestFactory) {
            return $this->requestFactory->createRequest(
                $method,
                $uri,
                $headers,
                $body
            );
        }

        if (is_string($body) && '' !== $body && null === $this->streamFactory) {
            throw new \RuntimeException('Cannot create request: A stream factory is required to create a request with a non-empty string body.');
        }

        $request = $this->requestFactory->createRequest($method, $uri);

        foreach ($headers as $key => $value) {
            $request = $request->withHeader($key, $value);
        }

        if (null !== $body && '' !== $body) {
            return $request->withBody(
                is_string($body) ? $this->streamFactory->createStream($body) : $body
            );
        }

        return $request;
    }

    private function createUri(
        string $operationHost,
        string $resourcePath,
        array $queryParams
    ): UriInterface {
        $parsedUrl = parse_url($operationHost);

        $host = $parsedUrl['host'] ?? null;
        $scheme = $parsedUrl['scheme'] ?? null;
        $basePath = $parsedUrl['path'] ?? null;
        $port = $parsedUrl['port'] ?? null;
        $user = $parsedUrl['user'] ?? null;
        $password = $parsedUrl['pass'] ?? null;

        $uri = $this->uriFactory->createUri($basePath . $resourcePath)
            ->withHost($host)
            ->withScheme($scheme)
            ->withPort($port)
            ->withQuery(ObjectSerializer::buildQuery($queryParams));

        if ($user) {
            return $uri->withUserInfo($user, $password);
        }

        return $uri;
    }

    /**
     * @return array<int, object|int|mixed[]|null>
     */
    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
			$request,
                        $response,
                        $exception
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }
}
