<?php

declare(strict_types=1);

/**
 * ServicePointsApi
 * PHP version 7.2
 *
 * @category Class
 * @package  Toppy\Sendcloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
/**
 * Sendcloud Public REST API
 *
 * Complete Sendcloud API v2 specification - merged from official Stoplight documentation bundles
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendcloud.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
namespace Toppy\Sendcloud\Api;

use GuzzleHttp\Psr7\MultipartStream;
use Http\Client\Common\Plugin\ErrorPlugin;
use Http\Client\Common\Plugin\RedirectPlugin;
use Http\Client\Common\PluginClient;
use Http\Client\Common\PluginClientFactory;
use Http\Client\Exception\HttpException;
use Http\Client\HttpAsyncClient;
use Http\Discovery\HttpAsyncClientDiscovery;
use Http\Discovery\Psr17FactoryDiscovery;
use Http\Discovery\Psr18ClientDiscovery;
use Http\Message\RequestFactory;
use Http\Promise\Promise;
use Toppy\Sendcloud\ApiException;
use Toppy\Sendcloud\Configuration;
use Toppy\Sendcloud\DebugPlugin;
use Toppy\Sendcloud\HeaderSelector;
use Toppy\Sendcloud\FormDataProcessor;
use Toppy\Sendcloud\ObjectSerializer;
use Psr\Http\Client\ClientExceptionInterface;
use Psr\Http\Client\ClientInterface;
use Psr\Http\Message\RequestFactoryInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\StreamFactoryInterface;
use Psr\Http\Message\UriFactoryInterface;
use Psr\Http\Message\UriInterface;
use function sprintf;

/**
 * ServicePointsApi Class Doc Comment
 *
 * @category Class
 * @package  Toppy\Sendcloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ServicePointsApi
{
    /**
     * @var PluginClient
     */
    protected $httpClient;

    /**
     * @var PluginClient
     */
    protected $httpAsyncClient;

    /**
     * @var UriFactoryInterface
     */
    protected $uriFactory;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var RequestFactoryInterface
     */
    protected $requestFactory;

    /**
     * @var StreamFactoryInterface
     */
    protected $streamFactory;

    /**
     * @param int $hostIndex
     */
    public function __construct(
        ?ClientInterface $httpClient = null,
        ?Configuration $configuration = null,
        ?HttpAsyncClient $httpAsyncClient = null,
        ?UriFactoryInterface $uriFactory = null,
        ?RequestFactoryInterface $requestFactory = null,
        ?StreamFactoryInterface $streamFactory = null,
        protected ?HeaderSelector $headerSelector = new HeaderSelector(),
        ?array $plugins = null,
        /**
         * @var int Host index
         */
        protected $hostIndex = 0
    ) {
        $this->config = $configuration ?? (new Configuration())->setHost('https://account.sendcloud.com');
        $this->requestFactory = $requestFactory ?? Psr17FactoryDiscovery::findRequestFactory();
        $this->streamFactory = $streamFactory ?? Psr17FactoryDiscovery::findStreamFactory();

        $plugins = $plugins ?? [
            new RedirectPlugin(['strict' => true]),
            new ErrorPlugin(),
        ];

        if ($this->config->getDebug()) {
            $plugins[] = new DebugPlugin(fopen($this->config->getDebugFile(), 'ab'));
        }

        $this->httpClient = (new PluginClientFactory())->createClient(
            $httpClient ?? Psr18ClientDiscovery::find(),
            $plugins
        );

        $this->httpAsyncClient = (new PluginClientFactory())->createClient(
            $httpAsyncClient ?? HttpAsyncClientDiscovery::find(),
            $plugins
        );

        $this->uriFactory = $uriFactory ?? Psr17FactoryDiscovery::findUriFactory();
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation scPublicV2ServicepointsGetCarriers
     *
     * Retrieve a list of service point carriers
     *
     * @param  string $accessToken A JSON Web Token encoding either an “id” (user ID) or “iid” (integration ID) property. Alternatively, a public API key. (optional)
     *
     * @throws \Toppy\Sendcloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return string[]|\Toppy\Sendcloud\Model\ScPublicV2ScpGetReturnById404Response
     */
    public function scPublicV2ServicepointsGetCarriers($accessToken = null)
    {
        [$response] = $this->scPublicV2ServicepointsGetCarriersWithHttpInfo($accessToken);
        return $response;
    }

    /**
     * Operation scPublicV2ServicepointsGetCarriersWithHttpInfo
     *
     * Retrieve a list of service point carriers
     *
     * @param  string $accessToken A JSON Web Token encoding either an “id” (user ID) or “iid” (integration ID) property. Alternatively, a public API key. (optional)
     *
     * @throws \Toppy\Sendcloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of string[]|\Toppy\Sendcloud\Model\ScPublicV2ScpGetReturnById404Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function scPublicV2ServicepointsGetCarriersWithHttpInfo($accessToken = null)
    {
        $request = $this->scPublicV2ServicepointsGetCarriersRequest($accessToken);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        'string[]',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        \Toppy\Sendcloud\Model\ScPublicV2ScpGetReturnById404Response::class,
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $request,
                    $response
                );
            }

            return $this->handleResponseWithDataType(
                'string[]',
                $request,
                $response,
            );
        } catch (ApiException $apiException) {
            switch ($apiException->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        'string[]',
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);
                    throw $apiException;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        \Toppy\Sendcloud\Model\ScPublicV2ScpGetReturnById404Response::class,
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);
                    throw $apiException;
            }
        

            throw $apiException;
        }
    }

    /**
     * Operation scPublicV2ServicepointsGetCarriersAsync
     *
     * Retrieve a list of service point carriers
     *
     * @param  string $accessToken A JSON Web Token encoding either an “id” (user ID) or “iid” (integration ID) property. Alternatively, a public API key. (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV2ServicepointsGetCarriersAsync($accessToken = null)
    {
        return $this->scPublicV2ServicepointsGetCarriersAsyncWithHttpInfo($accessToken)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation scPublicV2ServicepointsGetCarriersAsyncWithHttpInfo
     *
     * Retrieve a list of service point carriers
     *
     * @param  string $accessToken A JSON Web Token encoding either an “id” (user ID) or “iid” (integration ID) property. Alternatively, a public API key. (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV2ServicepointsGetCarriersAsyncWithHttpInfo($accessToken = null)
    {
        $returnType = 'string[]';
        $request = $this->scPublicV2ServicepointsGetCarriersRequest($accessToken);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $httpException) {
                    $response = $httpException->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $httpException->getRequest()->getUri()
                        ),
                        $httpException->getRequest(),
                        $httpException->getResponse(),
                        $httpException
                    );
                }
            );
    }

    /**
     * Create request for operation 'scPublicV2ServicepointsGetCarriers'
     *
     * @param  string $accessToken A JSON Web Token encoding either an “id” (user ID) or “iid” (integration ID) property. Alternatively, a public API key. (optional)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function scPublicV2ServicepointsGetCarriersRequest($accessToken = null)
    {

        $resourcePath = '/carriers';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // query params
        if ($accessToken !== null) {
            if(is_array($accessToken)) {
                foreach($accessToken as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['access_token'] = $accessToken;
            }
        }




        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }

    /**
     * Operation scPublicV2ServicepointsGetCheckAvailability
     *
     * Retrieve availability of a service point
     *
     * @param  float $servicePointId ID of the service point (required)
     * @param  string $accessToken A JSON Web Token encoding either an “id” (user ID) or “iid” (integration ID) property. Alternatively, a public API key. (optional)
     *
     * @throws \Toppy\Sendcloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return bool|\Toppy\Sendcloud\Model\ScPublicV2ScpGetReturnById404Response
     */
    public function scPublicV2ServicepointsGetCheckAvailability($servicePointId, $accessToken = null)
    {
        [$response] = $this->scPublicV2ServicepointsGetCheckAvailabilityWithHttpInfo($servicePointId, $accessToken);
        return $response;
    }

    /**
     * Operation scPublicV2ServicepointsGetCheckAvailabilityWithHttpInfo
     *
     * Retrieve availability of a service point
     *
     * @param  float $servicePointId ID of the service point (required)
     * @param  string $accessToken A JSON Web Token encoding either an “id” (user ID) or “iid” (integration ID) property. Alternatively, a public API key. (optional)
     *
     * @throws \Toppy\Sendcloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of bool|\Toppy\Sendcloud\Model\ScPublicV2ScpGetReturnById404Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function scPublicV2ServicepointsGetCheckAvailabilityWithHttpInfo($servicePointId, $accessToken = null)
    {
        $request = $this->scPublicV2ServicepointsGetCheckAvailabilityRequest($servicePointId, $accessToken);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        'bool',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        \Toppy\Sendcloud\Model\ScPublicV2ScpGetReturnById404Response::class,
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $request,
                    $response
                );
            }

            return $this->handleResponseWithDataType(
                'bool',
                $request,
                $response,
            );
        } catch (ApiException $apiException) {
            switch ($apiException->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        'bool',
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);
                    throw $apiException;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        \Toppy\Sendcloud\Model\ScPublicV2ScpGetReturnById404Response::class,
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);
                    throw $apiException;
            }
        

            throw $apiException;
        }
    }

    /**
     * Operation scPublicV2ServicepointsGetCheckAvailabilityAsync
     *
     * Retrieve availability of a service point
     *
     * @param  float $servicePointId ID of the service point (required)
     * @param  string $accessToken A JSON Web Token encoding either an “id” (user ID) or “iid” (integration ID) property. Alternatively, a public API key. (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV2ServicepointsGetCheckAvailabilityAsync($servicePointId, $accessToken = null)
    {
        return $this->scPublicV2ServicepointsGetCheckAvailabilityAsyncWithHttpInfo($servicePointId, $accessToken)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation scPublicV2ServicepointsGetCheckAvailabilityAsyncWithHttpInfo
     *
     * Retrieve availability of a service point
     *
     * @param  float $servicePointId ID of the service point (required)
     * @param  string $accessToken A JSON Web Token encoding either an “id” (user ID) or “iid” (integration ID) property. Alternatively, a public API key. (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV2ServicepointsGetCheckAvailabilityAsyncWithHttpInfo($servicePointId, $accessToken = null)
    {
        $returnType = 'bool';
        $request = $this->scPublicV2ServicepointsGetCheckAvailabilityRequest($servicePointId, $accessToken);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $httpException) {
                    $response = $httpException->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $httpException->getRequest()->getUri()
                        ),
                        $httpException->getRequest(),
                        $httpException->getResponse(),
                        $httpException
                    );
                }
            );
    }

    /**
     * Create request for operation 'scPublicV2ServicepointsGetCheckAvailability'
     *
     * @param  float $servicePointId ID of the service point (required)
     * @param  string $accessToken A JSON Web Token encoding either an “id” (user ID) or “iid” (integration ID) property. Alternatively, a public API key. (optional)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function scPublicV2ServicepointsGetCheckAvailabilityRequest($servicePointId, $accessToken = null)
    {
        // verify the required parameter 'servicePointId' is set
        if ($servicePointId === null || (is_array($servicePointId) && $servicePointId === [])) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $servicePointId when calling scPublicV2ServicepointsGetCheckAvailability'
            );
        }

        $resourcePath = '/service-points/{service_point_id}/check-availability';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // query params
        if ($accessToken !== null) {
            if(is_array($accessToken)) {
                foreach($accessToken as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['access_token'] = $accessToken;
            }
        }


        // path params
        $resourcePath = str_replace(
            '{service_point_id}',
            ObjectSerializer::toPathValue($servicePointId),
            $resourcePath
        );


        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }

    /**
     * Operation scPublicV2ServicepointsGetServicePointById
     *
     * Retrieve a service point
     *
     * @param  float $servicePointId ID of the service point (required)
     * @param  string $accessToken A JSON Web Token encoding either an “id” (user ID) or “iid” (integration ID) property. Alternatively, a public API key. (optional)
     *
     * @throws \Toppy\Sendcloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Toppy\Sendcloud\Model\ServicePoint|\Toppy\Sendcloud\Model\ScPublicV2ScpGetReturnById404Response
     */
    public function scPublicV2ServicepointsGetServicePointById($servicePointId, $accessToken = null)
    {
        [$response] = $this->scPublicV2ServicepointsGetServicePointByIdWithHttpInfo($servicePointId, $accessToken);
        return $response;
    }

    /**
     * Operation scPublicV2ServicepointsGetServicePointByIdWithHttpInfo
     *
     * Retrieve a service point
     *
     * @param  float $servicePointId ID of the service point (required)
     * @param  string $accessToken A JSON Web Token encoding either an “id” (user ID) or “iid” (integration ID) property. Alternatively, a public API key. (optional)
     *
     * @throws \Toppy\Sendcloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Toppy\Sendcloud\Model\ServicePoint|\Toppy\Sendcloud\Model\ScPublicV2ScpGetReturnById404Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function scPublicV2ServicepointsGetServicePointByIdWithHttpInfo($servicePointId, $accessToken = null)
    {
        $request = $this->scPublicV2ServicepointsGetServicePointByIdRequest($servicePointId, $accessToken);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        \Toppy\Sendcloud\Model\ServicePoint::class,
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        \Toppy\Sendcloud\Model\ScPublicV2ScpGetReturnById404Response::class,
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $request,
                    $response
                );
            }

            return $this->handleResponseWithDataType(
                \Toppy\Sendcloud\Model\ServicePoint::class,
                $request,
                $response,
            );
        } catch (ApiException $apiException) {
            switch ($apiException->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        \Toppy\Sendcloud\Model\ServicePoint::class,
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);
                    throw $apiException;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        \Toppy\Sendcloud\Model\ScPublicV2ScpGetReturnById404Response::class,
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);
                    throw $apiException;
            }
        

            throw $apiException;
        }
    }

    /**
     * Operation scPublicV2ServicepointsGetServicePointByIdAsync
     *
     * Retrieve a service point
     *
     * @param  float $servicePointId ID of the service point (required)
     * @param  string $accessToken A JSON Web Token encoding either an “id” (user ID) or “iid” (integration ID) property. Alternatively, a public API key. (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV2ServicepointsGetServicePointByIdAsync($servicePointId, $accessToken = null)
    {
        return $this->scPublicV2ServicepointsGetServicePointByIdAsyncWithHttpInfo($servicePointId, $accessToken)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation scPublicV2ServicepointsGetServicePointByIdAsyncWithHttpInfo
     *
     * Retrieve a service point
     *
     * @param  float $servicePointId ID of the service point (required)
     * @param  string $accessToken A JSON Web Token encoding either an “id” (user ID) or “iid” (integration ID) property. Alternatively, a public API key. (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV2ServicepointsGetServicePointByIdAsyncWithHttpInfo($servicePointId, $accessToken = null)
    {
        $returnType = \Toppy\Sendcloud\Model\ServicePoint::class;
        $request = $this->scPublicV2ServicepointsGetServicePointByIdRequest($servicePointId, $accessToken);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $httpException) {
                    $response = $httpException->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $httpException->getRequest()->getUri()
                        ),
                        $httpException->getRequest(),
                        $httpException->getResponse(),
                        $httpException
                    );
                }
            );
    }

    /**
     * Create request for operation 'scPublicV2ServicepointsGetServicePointById'
     *
     * @param  float $servicePointId ID of the service point (required)
     * @param  string $accessToken A JSON Web Token encoding either an “id” (user ID) or “iid” (integration ID) property. Alternatively, a public API key. (optional)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function scPublicV2ServicepointsGetServicePointByIdRequest($servicePointId, $accessToken = null)
    {
        // verify the required parameter 'servicePointId' is set
        if ($servicePointId === null || (is_array($servicePointId) && $servicePointId === [])) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $servicePointId when calling scPublicV2ServicepointsGetServicePointById'
            );
        }

        $resourcePath = '/service-points/{service_point_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // query params
        if ($accessToken !== null) {
            if(is_array($accessToken)) {
                foreach($accessToken as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['access_token'] = $accessToken;
            }
        }


        // path params
        $resourcePath = str_replace(
            '{service_point_id}',
            ObjectSerializer::toPathValue($servicePointId),
            $resourcePath
        );


        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }

    /**
     * Operation scPublicV2ServicepointsGetServicePoints
     *
     * Retrieve a list of service points
     *
     * @param  string $country A country ISO 2 code (required)
     * @param  string $xRequestedWith Identifies the request as one made using JavaScript (optional)
     * @param  string $accessToken A JSON Web Token encoding either an “id” (user ID) or “iid” (integration ID) property. Alternatively, a public API key. (optional)
     * @param  string $carrier A comma-separated list of carrier codes (stringified) (optional)
     * @param  string $latitude Used as a reference point to calculate the distance of the service point to the provided location. (optional)
     * @param  string $longitude Used as a reference point to calculate the distance of the service point to the provided location. (optional)
     * @param  string $neLatitude Latitude of the northeast corner of the bounding box. (optional)
     * @param  string $neLongitude Longitude of the northeast corner of the bounding box. (optional)
     * @param  string $swLatitude Latitude of the southwest corner of the bounding box. (optional)
     * @param  string $swLongitude Longitude of the southwest corner of the bounding box. (optional)
     * @param  string $address Address of the destination address. Can accept postal code instead of the street and the house number. (optional)
     * @param  string $city City of the destination address. (optional)
     * @param  string $postalCode Postal code of the destination address. Using &#x60;postal_code&#x60; will return you service points **located around that particular postal code**. (optional)
     * @param  string $houseNumber House number of the destination address. (optional)
     * @param  int $radius Radius (in meter) of a bounding circle. Can be used instead of the ne_latitude, ne_longitude, sw_latitude, and sw_longitude parameters to define a bounding box. Minimum value: 100 meters. Maximum value: 50 000 meters. (optional)
     * @param  float $weight Weight (in kg.) of the parcel to be shipped to the service points. Certain carriers impose limits for certain service points that cannot accept parcels above a certain weight limit. (optional)
     * @param  string $pudoId DPD-specific query parameter. (optional)
     * @param  string $shopType Filters results by their shop type. (optional)
     * @param  string $generalShopType Filters results by general shop type. Accepts a single value (e.g., &#x60;servicepoint&#x60;) or a comma-separated list of values (e.g., &#x60;servicepoint,locker,post_office&#x60;).  Possible options: - &#x60;servicepoint&#x60; - &#x60;locker&#x60; - &#x60;post_office&#x60; - &#x60;carrier_depot&#x60; (optional)
     *
     * @throws \Toppy\Sendcloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Toppy\Sendcloud\Model\ServicePoint[]|\Toppy\Sendcloud\Model\ScPublicV2ServicepointsGetServicePoints400Response
     */
    public function scPublicV2ServicepointsGetServicePoints($country, $xRequestedWith = null, $accessToken = null, $carrier = null, $latitude = null, $longitude = null, $neLatitude = null, $neLongitude = null, $swLatitude = null, $swLongitude = null, $address = null, $city = null, $postalCode = null, $houseNumber = null, $radius = null, $weight = null, $pudoId = null, $shopType = null, $generalShopType = null)
    {
        [$response] = $this->scPublicV2ServicepointsGetServicePointsWithHttpInfo($country, $xRequestedWith, $accessToken, $carrier, $latitude, $longitude, $neLatitude, $neLongitude, $swLatitude, $swLongitude, $address, $city, $postalCode, $houseNumber, $radius, $weight, $pudoId, $shopType, $generalShopType);
        return $response;
    }

    /**
     * Operation scPublicV2ServicepointsGetServicePointsWithHttpInfo
     *
     * Retrieve a list of service points
     *
     * @param  string $country A country ISO 2 code (required)
     * @param  string $xRequestedWith Identifies the request as one made using JavaScript (optional)
     * @param  string $accessToken A JSON Web Token encoding either an “id” (user ID) or “iid” (integration ID) property. Alternatively, a public API key. (optional)
     * @param  string $carrier A comma-separated list of carrier codes (stringified) (optional)
     * @param  string $latitude Used as a reference point to calculate the distance of the service point to the provided location. (optional)
     * @param  string $longitude Used as a reference point to calculate the distance of the service point to the provided location. (optional)
     * @param  string $neLatitude Latitude of the northeast corner of the bounding box. (optional)
     * @param  string $neLongitude Longitude of the northeast corner of the bounding box. (optional)
     * @param  string $swLatitude Latitude of the southwest corner of the bounding box. (optional)
     * @param  string $swLongitude Longitude of the southwest corner of the bounding box. (optional)
     * @param  string $address Address of the destination address. Can accept postal code instead of the street and the house number. (optional)
     * @param  string $city City of the destination address. (optional)
     * @param  string $postalCode Postal code of the destination address. Using &#x60;postal_code&#x60; will return you service points **located around that particular postal code**. (optional)
     * @param  string $houseNumber House number of the destination address. (optional)
     * @param  int $radius Radius (in meter) of a bounding circle. Can be used instead of the ne_latitude, ne_longitude, sw_latitude, and sw_longitude parameters to define a bounding box. Minimum value: 100 meters. Maximum value: 50 000 meters. (optional)
     * @param  float $weight Weight (in kg.) of the parcel to be shipped to the service points. Certain carriers impose limits for certain service points that cannot accept parcels above a certain weight limit. (optional)
     * @param  string $pudoId DPD-specific query parameter. (optional)
     * @param  string $shopType Filters results by their shop type. (optional)
     * @param  string $generalShopType Filters results by general shop type. Accepts a single value (e.g., &#x60;servicepoint&#x60;) or a comma-separated list of values (e.g., &#x60;servicepoint,locker,post_office&#x60;).  Possible options: - &#x60;servicepoint&#x60; - &#x60;locker&#x60; - &#x60;post_office&#x60; - &#x60;carrier_depot&#x60; (optional)
     *
     * @throws \Toppy\Sendcloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Toppy\Sendcloud\Model\ServicePoint[]|\Toppy\Sendcloud\Model\ScPublicV2ServicepointsGetServicePoints400Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function scPublicV2ServicepointsGetServicePointsWithHttpInfo($country, $xRequestedWith = null, $accessToken = null, $carrier = null, $latitude = null, $longitude = null, $neLatitude = null, $neLongitude = null, $swLatitude = null, $swLongitude = null, $address = null, $city = null, $postalCode = null, $houseNumber = null, $radius = null, $weight = null, $pudoId = null, $shopType = null, $generalShopType = null)
    {
        $request = $this->scPublicV2ServicepointsGetServicePointsRequest($country, $xRequestedWith, $accessToken, $carrier, $latitude, $longitude, $neLatitude, $neLongitude, $swLatitude, $swLongitude, $address, $city, $postalCode, $houseNumber, $radius, $weight, $pudoId, $shopType, $generalShopType);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Toppy\Sendcloud\Model\ServicePoint[]',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        \Toppy\Sendcloud\Model\ScPublicV2ServicepointsGetServicePoints400Response::class,
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $request,
                    $response
                );
            }

            return $this->handleResponseWithDataType(
                '\Toppy\Sendcloud\Model\ServicePoint[]',
                $request,
                $response,
            );
        } catch (ApiException $apiException) {
            switch ($apiException->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        '\Toppy\Sendcloud\Model\ServicePoint[]',
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);
                    throw $apiException;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        \Toppy\Sendcloud\Model\ScPublicV2ServicepointsGetServicePoints400Response::class,
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);
                    throw $apiException;
            }
        

            throw $apiException;
        }
    }

    /**
     * Operation scPublicV2ServicepointsGetServicePointsAsync
     *
     * Retrieve a list of service points
     *
     * @param  string $country A country ISO 2 code (required)
     * @param  string $xRequestedWith Identifies the request as one made using JavaScript (optional)
     * @param  string $accessToken A JSON Web Token encoding either an “id” (user ID) or “iid” (integration ID) property. Alternatively, a public API key. (optional)
     * @param  string $carrier A comma-separated list of carrier codes (stringified) (optional)
     * @param  string $latitude Used as a reference point to calculate the distance of the service point to the provided location. (optional)
     * @param  string $longitude Used as a reference point to calculate the distance of the service point to the provided location. (optional)
     * @param  string $neLatitude Latitude of the northeast corner of the bounding box. (optional)
     * @param  string $neLongitude Longitude of the northeast corner of the bounding box. (optional)
     * @param  string $swLatitude Latitude of the southwest corner of the bounding box. (optional)
     * @param  string $swLongitude Longitude of the southwest corner of the bounding box. (optional)
     * @param  string $address Address of the destination address. Can accept postal code instead of the street and the house number. (optional)
     * @param  string $city City of the destination address. (optional)
     * @param  string $postalCode Postal code of the destination address. Using &#x60;postal_code&#x60; will return you service points **located around that particular postal code**. (optional)
     * @param  string $houseNumber House number of the destination address. (optional)
     * @param  int $radius Radius (in meter) of a bounding circle. Can be used instead of the ne_latitude, ne_longitude, sw_latitude, and sw_longitude parameters to define a bounding box. Minimum value: 100 meters. Maximum value: 50 000 meters. (optional)
     * @param  float $weight Weight (in kg.) of the parcel to be shipped to the service points. Certain carriers impose limits for certain service points that cannot accept parcels above a certain weight limit. (optional)
     * @param  string $pudoId DPD-specific query parameter. (optional)
     * @param  string $shopType Filters results by their shop type. (optional)
     * @param  string $generalShopType Filters results by general shop type. Accepts a single value (e.g., &#x60;servicepoint&#x60;) or a comma-separated list of values (e.g., &#x60;servicepoint,locker,post_office&#x60;).  Possible options: - &#x60;servicepoint&#x60; - &#x60;locker&#x60; - &#x60;post_office&#x60; - &#x60;carrier_depot&#x60; (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV2ServicepointsGetServicePointsAsync($country, $xRequestedWith = null, $accessToken = null, $carrier = null, $latitude = null, $longitude = null, $neLatitude = null, $neLongitude = null, $swLatitude = null, $swLongitude = null, $address = null, $city = null, $postalCode = null, $houseNumber = null, $radius = null, $weight = null, $pudoId = null, $shopType = null, $generalShopType = null)
    {
        return $this->scPublicV2ServicepointsGetServicePointsAsyncWithHttpInfo($country, $xRequestedWith, $accessToken, $carrier, $latitude, $longitude, $neLatitude, $neLongitude, $swLatitude, $swLongitude, $address, $city, $postalCode, $houseNumber, $radius, $weight, $pudoId, $shopType, $generalShopType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation scPublicV2ServicepointsGetServicePointsAsyncWithHttpInfo
     *
     * Retrieve a list of service points
     *
     * @param  string $country A country ISO 2 code (required)
     * @param  string $xRequestedWith Identifies the request as one made using JavaScript (optional)
     * @param  string $accessToken A JSON Web Token encoding either an “id” (user ID) or “iid” (integration ID) property. Alternatively, a public API key. (optional)
     * @param  string $carrier A comma-separated list of carrier codes (stringified) (optional)
     * @param  string $latitude Used as a reference point to calculate the distance of the service point to the provided location. (optional)
     * @param  string $longitude Used as a reference point to calculate the distance of the service point to the provided location. (optional)
     * @param  string $neLatitude Latitude of the northeast corner of the bounding box. (optional)
     * @param  string $neLongitude Longitude of the northeast corner of the bounding box. (optional)
     * @param  string $swLatitude Latitude of the southwest corner of the bounding box. (optional)
     * @param  string $swLongitude Longitude of the southwest corner of the bounding box. (optional)
     * @param  string $address Address of the destination address. Can accept postal code instead of the street and the house number. (optional)
     * @param  string $city City of the destination address. (optional)
     * @param  string $postalCode Postal code of the destination address. Using &#x60;postal_code&#x60; will return you service points **located around that particular postal code**. (optional)
     * @param  string $houseNumber House number of the destination address. (optional)
     * @param  int $radius Radius (in meter) of a bounding circle. Can be used instead of the ne_latitude, ne_longitude, sw_latitude, and sw_longitude parameters to define a bounding box. Minimum value: 100 meters. Maximum value: 50 000 meters. (optional)
     * @param  float $weight Weight (in kg.) of the parcel to be shipped to the service points. Certain carriers impose limits for certain service points that cannot accept parcels above a certain weight limit. (optional)
     * @param  string $pudoId DPD-specific query parameter. (optional)
     * @param  string $shopType Filters results by their shop type. (optional)
     * @param  string $generalShopType Filters results by general shop type. Accepts a single value (e.g., &#x60;servicepoint&#x60;) or a comma-separated list of values (e.g., &#x60;servicepoint,locker,post_office&#x60;).  Possible options: - &#x60;servicepoint&#x60; - &#x60;locker&#x60; - &#x60;post_office&#x60; - &#x60;carrier_depot&#x60; (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV2ServicepointsGetServicePointsAsyncWithHttpInfo($country, $xRequestedWith = null, $accessToken = null, $carrier = null, $latitude = null, $longitude = null, $neLatitude = null, $neLongitude = null, $swLatitude = null, $swLongitude = null, $address = null, $city = null, $postalCode = null, $houseNumber = null, $radius = null, $weight = null, $pudoId = null, $shopType = null, $generalShopType = null)
    {
        $returnType = '\Toppy\Sendcloud\Model\ServicePoint[]';
        $request = $this->scPublicV2ServicepointsGetServicePointsRequest($country, $xRequestedWith, $accessToken, $carrier, $latitude, $longitude, $neLatitude, $neLongitude, $swLatitude, $swLongitude, $address, $city, $postalCode, $houseNumber, $radius, $weight, $pudoId, $shopType, $generalShopType);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $httpException) {
                    $response = $httpException->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $httpException->getRequest()->getUri()
                        ),
                        $httpException->getRequest(),
                        $httpException->getResponse(),
                        $httpException
                    );
                }
            );
    }

    /**
     * Create request for operation 'scPublicV2ServicepointsGetServicePoints'
     *
     * @param  string $country A country ISO 2 code (required)
     * @param  string $xRequestedWith Identifies the request as one made using JavaScript (optional)
     * @param  string $accessToken A JSON Web Token encoding either an “id” (user ID) or “iid” (integration ID) property. Alternatively, a public API key. (optional)
     * @param  string $carrier A comma-separated list of carrier codes (stringified) (optional)
     * @param  string $latitude Used as a reference point to calculate the distance of the service point to the provided location. (optional)
     * @param  string $longitude Used as a reference point to calculate the distance of the service point to the provided location. (optional)
     * @param  string $neLatitude Latitude of the northeast corner of the bounding box. (optional)
     * @param  string $neLongitude Longitude of the northeast corner of the bounding box. (optional)
     * @param  string $swLatitude Latitude of the southwest corner of the bounding box. (optional)
     * @param  string $swLongitude Longitude of the southwest corner of the bounding box. (optional)
     * @param  string $address Address of the destination address. Can accept postal code instead of the street and the house number. (optional)
     * @param  string $city City of the destination address. (optional)
     * @param  string $postalCode Postal code of the destination address. Using &#x60;postal_code&#x60; will return you service points **located around that particular postal code**. (optional)
     * @param  string $houseNumber House number of the destination address. (optional)
     * @param  int $radius Radius (in meter) of a bounding circle. Can be used instead of the ne_latitude, ne_longitude, sw_latitude, and sw_longitude parameters to define a bounding box. Minimum value: 100 meters. Maximum value: 50 000 meters. (optional)
     * @param  float $weight Weight (in kg.) of the parcel to be shipped to the service points. Certain carriers impose limits for certain service points that cannot accept parcels above a certain weight limit. (optional)
     * @param  string $pudoId DPD-specific query parameter. (optional)
     * @param  string $shopType Filters results by their shop type. (optional)
     * @param  string $generalShopType Filters results by general shop type. Accepts a single value (e.g., &#x60;servicepoint&#x60;) or a comma-separated list of values (e.g., &#x60;servicepoint,locker,post_office&#x60;).  Possible options: - &#x60;servicepoint&#x60; - &#x60;locker&#x60; - &#x60;post_office&#x60; - &#x60;carrier_depot&#x60; (optional)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function scPublicV2ServicepointsGetServicePointsRequest($country, $xRequestedWith = null, $accessToken = null, $carrier = null, $latitude = null, $longitude = null, $neLatitude = null, $neLongitude = null, $swLatitude = null, $swLongitude = null, $address = null, $city = null, $postalCode = null, $houseNumber = null, $radius = null, $weight = null, $pudoId = null, $shopType = null, $generalShopType = null)
    {
        // verify the required parameter 'country' is set
        if ($country === null || (is_array($country) && $country === [])) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $country when calling scPublicV2ServicepointsGetServicePoints'
            );
        }

        if ($radius !== null && $radius > 50000) {
            throw new \InvalidArgumentException('invalid value for "$radius" when calling ServicePointsApi.scPublicV2ServicepointsGetServicePoints, must be smaller than or equal to 50000.');
        }

        if ($radius !== null && $radius < 100) {
            throw new \InvalidArgumentException('invalid value for "$radius" when calling ServicePointsApi.scPublicV2ServicepointsGetServicePoints, must be bigger than or equal to 100.');
        }

        if ($pudoId !== null && strlen($pudoId) > 7) {
            throw new \InvalidArgumentException('invalid length for "$pudoId" when calling ServicePointsApi.scPublicV2ServicepointsGetServicePoints, must be smaller than or equal to 7.');
        }


        $resourcePath = '/service-points';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // query params
        if ($accessToken !== null) {
            if(is_array($accessToken)) {
                foreach($accessToken as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['access_token'] = $accessToken;
            }
        }

        // query params
        if(is_array($country)) {
            foreach($country as $key => $value) {
                $queryParams[$key] = $value;
            }
        }
        else {
            $queryParams['country'] = $country;
        }

        // query params
        if ($carrier !== null) {
            if(is_array($carrier)) {
                foreach($carrier as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['carrier'] = $carrier;
            }
        }

        // query params
        if ($latitude !== null) {
            if(is_array($latitude)) {
                foreach($latitude as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['latitude'] = $latitude;
            }
        }

        // query params
        if ($longitude !== null) {
            if(is_array($longitude)) {
                foreach($longitude as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['longitude'] = $longitude;
            }
        }

        // query params
        if ($neLatitude !== null) {
            if(is_array($neLatitude)) {
                foreach($neLatitude as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['ne_latitude'] = $neLatitude;
            }
        }

        // query params
        if ($neLongitude !== null) {
            if(is_array($neLongitude)) {
                foreach($neLongitude as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['ne_longitude'] = $neLongitude;
            }
        }

        // query params
        if ($swLatitude !== null) {
            if(is_array($swLatitude)) {
                foreach($swLatitude as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['sw_latitude'] = $swLatitude;
            }
        }

        // query params
        if ($swLongitude !== null) {
            if(is_array($swLongitude)) {
                foreach($swLongitude as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['sw_longitude'] = $swLongitude;
            }
        }

        // query params
        if ($address !== null) {
            if(is_array($address)) {
                foreach($address as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['address'] = $address;
            }
        }

        // query params
        if ($city !== null) {
            if(is_array($city)) {
                foreach($city as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['city'] = $city;
            }
        }

        // query params
        if ($postalCode !== null) {
            if(is_array($postalCode)) {
                foreach($postalCode as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['postal_code'] = $postalCode;
            }
        }

        // query params
        if ($houseNumber !== null) {
            if(is_array($houseNumber)) {
                foreach($houseNumber as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['house_number'] = $houseNumber;
            }
        }

        // query params
        if ($radius !== null) {
            if(is_array($radius)) {
                foreach($radius as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['radius'] = $radius;
            }
        }

        // query params
        if ($weight !== null) {
            if(is_array($weight)) {
                foreach($weight as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['weight'] = $weight;
            }
        }

        // query params
        if ($pudoId !== null) {
            if(is_array($pudoId)) {
                foreach($pudoId as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['pudo_id'] = $pudoId;
            }
        }

        // query params
        if ($shopType !== null) {
            if(is_array($shopType)) {
                foreach($shopType as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['shop_type'] = $shopType;
            }
        }

        // query params
        if ($generalShopType !== null) {
            if(is_array($generalShopType)) {
                foreach($generalShopType as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['general_shop_type'] = $generalShopType;
            }
        }

        // header params
        if ($xRequestedWith !== null) {
            $headerParams['X-Requested-With'] = ObjectSerializer::toHeaderValue($xRequestedWith);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }


    /**
     * @param string|UriInterface $uri
     * @param string[] $headers
     * @param string|StreamInterface|null $body
     *
     */
    protected function createRequest(string $method, $uri, array $headers = [], $body = null): RequestInterface
    {
        if ($this->requestFactory instanceof RequestFactory) {
            return $this->requestFactory->createRequest(
                $method,
                $uri,
                $headers,
                $body
            );
        }

        if (is_string($body) && '' !== $body && null === $this->streamFactory) {
            throw new \RuntimeException('Cannot create request: A stream factory is required to create a request with a non-empty string body.');
        }

        $request = $this->requestFactory->createRequest($method, $uri);

        foreach ($headers as $key => $value) {
            $request = $request->withHeader($key, $value);
        }

        if (null !== $body && '' !== $body) {
            return $request->withBody(
                is_string($body) ? $this->streamFactory->createStream($body) : $body
            );
        }

        return $request;
    }

    private function createUri(
        string $operationHost,
        string $resourcePath,
        array $queryParams
    ): UriInterface {
        $parsedUrl = parse_url($operationHost);

        $host = $parsedUrl['host'] ?? null;
        $scheme = $parsedUrl['scheme'] ?? null;
        $basePath = $parsedUrl['path'] ?? null;
        $port = $parsedUrl['port'] ?? null;
        $user = $parsedUrl['user'] ?? null;
        $password = $parsedUrl['pass'] ?? null;

        $uri = $this->uriFactory->createUri($basePath . $resourcePath)
            ->withHost($host)
            ->withScheme($scheme)
            ->withPort($port)
            ->withQuery(ObjectSerializer::buildQuery($queryParams));

        if ($user) {
            return $uri->withUserInfo($user, $password);
        }

        return $uri;
    }

    /**
     * @return array<int, object|int|mixed[]|null>
     */
    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
			$request,
                        $response,
                        $exception
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }
}
