<?php

declare(strict_types=1);

/**
 * ShippingProductsApi
 * PHP version 7.2
 *
 * @category Class
 * @package  Toppy\Sendcloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
/**
 * Sendcloud Public REST API
 *
 * Complete Sendcloud API v2 specification - merged from official Stoplight documentation bundles
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendcloud.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
namespace Toppy\Sendcloud\Api;

use GuzzleHttp\Psr7\MultipartStream;
use Http\Client\Common\Plugin\ErrorPlugin;
use Http\Client\Common\Plugin\RedirectPlugin;
use Http\Client\Common\PluginClient;
use Http\Client\Common\PluginClientFactory;
use Http\Client\Exception\HttpException;
use Http\Client\HttpAsyncClient;
use Http\Discovery\HttpAsyncClientDiscovery;
use Http\Discovery\Psr17FactoryDiscovery;
use Http\Discovery\Psr18ClientDiscovery;
use Http\Message\RequestFactory;
use Http\Promise\Promise;
use Toppy\Sendcloud\ApiException;
use Toppy\Sendcloud\Configuration;
use Toppy\Sendcloud\DebugPlugin;
use Toppy\Sendcloud\HeaderSelector;
use Toppy\Sendcloud\FormDataProcessor;
use Toppy\Sendcloud\ObjectSerializer;
use Psr\Http\Client\ClientExceptionInterface;
use Psr\Http\Client\ClientInterface;
use Psr\Http\Message\RequestFactoryInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\StreamFactoryInterface;
use Psr\Http\Message\UriFactoryInterface;
use Psr\Http\Message\UriInterface;
use function sprintf;

/**
 * ShippingProductsApi Class Doc Comment
 *
 * @category Class
 * @package  Toppy\Sendcloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ShippingProductsApi
{
    /**
     * @var PluginClient
     */
    protected $httpClient;

    /**
     * @var PluginClient
     */
    protected $httpAsyncClient;

    /**
     * @var UriFactoryInterface
     */
    protected $uriFactory;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var RequestFactoryInterface
     */
    protected $requestFactory;

    /**
     * @var StreamFactoryInterface
     */
    protected $streamFactory;

    /**
     * @param int $hostIndex
     */
    public function __construct(
        ?ClientInterface $httpClient = null,
        ?Configuration $configuration = null,
        ?HttpAsyncClient $httpAsyncClient = null,
        ?UriFactoryInterface $uriFactory = null,
        ?RequestFactoryInterface $requestFactory = null,
        ?StreamFactoryInterface $streamFactory = null,
        protected ?HeaderSelector $headerSelector = new HeaderSelector(),
        ?array $plugins = null,
        /**
         * @var int Host index
         */
        protected $hostIndex = 0
    ) {
        $this->config = $configuration ?? (new Configuration())->setHost('https://account.sendcloud.com');
        $this->requestFactory = $requestFactory ?? Psr17FactoryDiscovery::findRequestFactory();
        $this->streamFactory = $streamFactory ?? Psr17FactoryDiscovery::findStreamFactory();

        $plugins = $plugins ?? [
            new RedirectPlugin(['strict' => true]),
            new ErrorPlugin(),
        ];

        if ($this->config->getDebug()) {
            $plugins[] = new DebugPlugin(fopen($this->config->getDebugFile(), 'ab'));
        }

        $this->httpClient = (new PluginClientFactory())->createClient(
            $httpClient ?? Psr18ClientDiscovery::find(),
            $plugins
        );

        $this->httpAsyncClient = (new PluginClientFactory())->createClient(
            $httpAsyncClient ?? HttpAsyncClientDiscovery::find(),
            $plugins
        );

        $this->uriFactory = $uriFactory ?? Psr17FactoryDiscovery::findUriFactory();
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation scPublicV2ScpGetRetrieveAllShippingFunctionalities
     *
     * Retrieve a list of shipping functionalities
     *
     *
     * @throws \Toppy\Sendcloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Toppy\Sendcloud\Model\ShippingFunctionalityDefinitions
     */
    public function scPublicV2ScpGetRetrieveAllShippingFunctionalities()
    {
        [$response] = $this->scPublicV2ScpGetRetrieveAllShippingFunctionalitiesWithHttpInfo();
        return $response;
    }

    /**
     * Operation scPublicV2ScpGetRetrieveAllShippingFunctionalitiesWithHttpInfo
     *
     * Retrieve a list of shipping functionalities
     *
     *
     * @throws \Toppy\Sendcloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Toppy\Sendcloud\Model\ShippingFunctionalityDefinitions, HTTP status code, HTTP response headers (array of strings)
     */
    public function scPublicV2ScpGetRetrieveAllShippingFunctionalitiesWithHttpInfo()
    {
        $request = $this->scPublicV2ScpGetRetrieveAllShippingFunctionalitiesRequest();

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            if ($statusCode === 200) {
                return $this->handleResponseWithDataType(
                    \Toppy\Sendcloud\Model\ShippingFunctionalityDefinitions::class,
                    $request,
                    $response,
                );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $request,
                    $response
                );
            }

            return $this->handleResponseWithDataType(
                \Toppy\Sendcloud\Model\ShippingFunctionalityDefinitions::class,
                $request,
                $response,
            );
        } catch (ApiException $apiException) {
            if ($apiException->getCode() === 200) {
                $data = ObjectSerializer::deserialize(
                    $apiException->getResponseBody(),
                    \Toppy\Sendcloud\Model\ShippingFunctionalityDefinitions::class,
                    $apiException->getResponseHeaders()
                );
                $apiException->setResponseObject($data);
                throw $apiException;
            }
        

            throw $apiException;
        }
    }

    /**
     * Operation scPublicV2ScpGetRetrieveAllShippingFunctionalitiesAsync
     *
     * Retrieve a list of shipping functionalities
     *
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV2ScpGetRetrieveAllShippingFunctionalitiesAsync()
    {
        return $this->scPublicV2ScpGetRetrieveAllShippingFunctionalitiesAsyncWithHttpInfo()
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation scPublicV2ScpGetRetrieveAllShippingFunctionalitiesAsyncWithHttpInfo
     *
     * Retrieve a list of shipping functionalities
     *
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV2ScpGetRetrieveAllShippingFunctionalitiesAsyncWithHttpInfo()
    {
        $returnType = \Toppy\Sendcloud\Model\ShippingFunctionalityDefinitions::class;
        $request = $this->scPublicV2ScpGetRetrieveAllShippingFunctionalitiesRequest();

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $httpException) {
                    $response = $httpException->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $httpException->getRequest()->getUri()
                        ),
                        $httpException->getRequest(),
                        $httpException->getResponse(),
                        $httpException
                    );
                }
            );
    }

    /**
     * Create request for operation 'scPublicV2ScpGetRetrieveAllShippingFunctionalities'
     *
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function scPublicV2ScpGetRetrieveAllShippingFunctionalitiesRequest()
    {

        $resourcePath = '/shipping-functionalities';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }

    /**
     * Operation scPublicV2ScpGetRetrieveAllShippingProducts
     *
     * Retrieve a list of shipping products
     *
     * @param  string $fromCountry A country ISO 2 code for a from country (origin country). (required)
     * @param  \Toppy\Sendcloud\Model\CountryCodes $toCountry A country ISO 2 code for the recipient country. Required if the carrier is zonal or &#x60;contract_pricing&#x60; parameter is provided. (optional)
     * @param  string $carrier A carrier code. (optional)
     * @param  int $contract The contract id used for shipping product/method filtering. It has a similar effect as using the &#x60;carrier&#x60; parameter. If the &#x60;contract_pricing&#x60; parameter is used, the carrier is used to provide the correct contract pricing. Only required if multiple contract prices exist for the same shipping method. (optional)
     * @param  int $weight The weight of the shipment. (optional)
     * @param  string $weightUnit The unit for the shipment weight. Required if the &#x60;weight&#x60; parameter is provided. (optional)
     * @param  int $length The length of the shipment. Required if the &#x60;width&#x60; and/or &#x60;height&#x60; parameters are provided. (optional)
     * @param  string $lengthUnit The unit for the shipment length. Required if the &#x60;length&#x60; parameter is provided. (optional)
     * @param  int $width The width of the shipment. Required if the &#x60;length&#x60; and/or &#x60;height&#x60; parameters are provided. (optional)
     * @param  string $widthUnit The unit for the shipment width. Required if the “width” parameter is provided. (optional)
     * @param  int $height The height of the shipment. Required if the “width” and/or “length” parameters are provided. (optional)
     * @param  string $heightUnit The unit for the shipment height. Required if the “height” parameter is provided. (optional)
     * @param  int $leadTimeHours Filters shipping products (rather its associated shipping methods) by their transit time. This is the estimated time a shipment takes between a parcel is being picked up by a carrier and it reaching its destination. This parameter supports comparison operators (e.g. &#x60;lead_time_hours[gte]&#x3D;12&#x60; for filtering out shipments that have less than 12 hours transit time or &#x60;lead_time_hours[gte&#x3D;24]&amp;lead_time_hours[lte]&#x3D;48&#x60; for only including shipping products whose methods have a transit time between 24 and 48 hours). Available operators are “eq” (equal), “gt” (greater than), “lt” (less than), “gte” (greater than or equal), and “lte” (less than or equal). (optional)
     * @param  bool $contractPricing Whether to include contract prices in the response. This parameter is only available to users upon request. Please contact customer support. (optional)
     * @param  string $fromPostalCode Postal code of the sender. Required if the carrier is zonal. (optional)
     * @param  string $toPostalCode Postal code of the recipient. Required if the carrier is zonal. (optional)
     * @param  bool $returns If set to &#x60;true&#x60; the endpoint will return shipping methods which can be used for making a return  shipment. (optional, default to false)
     *
     * @throws \Toppy\Sendcloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Toppy\Sendcloud\Model\ShippingProduct[]|\Toppy\Sendcloud\Model\ScPublicV2AddressesGetSenderAddressById404Response
     */
    public function scPublicV2ScpGetRetrieveAllShippingProducts($fromCountry, $toCountry = null, $carrier = null, $contract = null, $weight = null, $weightUnit = null, $length = null, $lengthUnit = null, $width = null, $widthUnit = null, $height = null, $heightUnit = null, $leadTimeHours = null, $contractPricing = null, $fromPostalCode = null, $toPostalCode = null, $returns = false)
    {
        [$response] = $this->scPublicV2ScpGetRetrieveAllShippingProductsWithHttpInfo($fromCountry, $toCountry, $carrier, $contract, $weight, $weightUnit, $length, $lengthUnit, $width, $widthUnit, $height, $heightUnit, $leadTimeHours, $contractPricing, $fromPostalCode, $toPostalCode, $returns);
        return $response;
    }

    /**
     * Operation scPublicV2ScpGetRetrieveAllShippingProductsWithHttpInfo
     *
     * Retrieve a list of shipping products
     *
     * @param  string $fromCountry A country ISO 2 code for a from country (origin country). (required)
     * @param  \Toppy\Sendcloud\Model\CountryCodes $toCountry A country ISO 2 code for the recipient country. Required if the carrier is zonal or &#x60;contract_pricing&#x60; parameter is provided. (optional)
     * @param  string $carrier A carrier code. (optional)
     * @param  int $contract The contract id used for shipping product/method filtering. It has a similar effect as using the &#x60;carrier&#x60; parameter. If the &#x60;contract_pricing&#x60; parameter is used, the carrier is used to provide the correct contract pricing. Only required if multiple contract prices exist for the same shipping method. (optional)
     * @param  int $weight The weight of the shipment. (optional)
     * @param  string $weightUnit The unit for the shipment weight. Required if the &#x60;weight&#x60; parameter is provided. (optional)
     * @param  int $length The length of the shipment. Required if the &#x60;width&#x60; and/or &#x60;height&#x60; parameters are provided. (optional)
     * @param  string $lengthUnit The unit for the shipment length. Required if the &#x60;length&#x60; parameter is provided. (optional)
     * @param  int $width The width of the shipment. Required if the &#x60;length&#x60; and/or &#x60;height&#x60; parameters are provided. (optional)
     * @param  string $widthUnit The unit for the shipment width. Required if the “width” parameter is provided. (optional)
     * @param  int $height The height of the shipment. Required if the “width” and/or “length” parameters are provided. (optional)
     * @param  string $heightUnit The unit for the shipment height. Required if the “height” parameter is provided. (optional)
     * @param  int $leadTimeHours Filters shipping products (rather its associated shipping methods) by their transit time. This is the estimated time a shipment takes between a parcel is being picked up by a carrier and it reaching its destination. This parameter supports comparison operators (e.g. &#x60;lead_time_hours[gte]&#x3D;12&#x60; for filtering out shipments that have less than 12 hours transit time or &#x60;lead_time_hours[gte&#x3D;24]&amp;lead_time_hours[lte]&#x3D;48&#x60; for only including shipping products whose methods have a transit time between 24 and 48 hours). Available operators are “eq” (equal), “gt” (greater than), “lt” (less than), “gte” (greater than or equal), and “lte” (less than or equal). (optional)
     * @param  bool $contractPricing Whether to include contract prices in the response. This parameter is only available to users upon request. Please contact customer support. (optional)
     * @param  string $fromPostalCode Postal code of the sender. Required if the carrier is zonal. (optional)
     * @param  string $toPostalCode Postal code of the recipient. Required if the carrier is zonal. (optional)
     * @param  bool $returns If set to &#x60;true&#x60; the endpoint will return shipping methods which can be used for making a return  shipment. (optional, default to false)
     *
     * @throws \Toppy\Sendcloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Toppy\Sendcloud\Model\ShippingProduct[]|\Toppy\Sendcloud\Model\ScPublicV2AddressesGetSenderAddressById404Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function scPublicV2ScpGetRetrieveAllShippingProductsWithHttpInfo($fromCountry, $toCountry = null, $carrier = null, $contract = null, $weight = null, $weightUnit = null, $length = null, $lengthUnit = null, $width = null, $widthUnit = null, $height = null, $heightUnit = null, $leadTimeHours = null, $contractPricing = null, $fromPostalCode = null, $toPostalCode = null, $returns = false)
    {
        $request = $this->scPublicV2ScpGetRetrieveAllShippingProductsRequest($fromCountry, $toCountry, $carrier, $contract, $weight, $weightUnit, $length, $lengthUnit, $width, $widthUnit, $height, $heightUnit, $leadTimeHours, $contractPricing, $fromPostalCode, $toPostalCode, $returns);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Toppy\Sendcloud\Model\ShippingProduct[]',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        \Toppy\Sendcloud\Model\ScPublicV2AddressesGetSenderAddressById404Response::class,
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $request,
                    $response
                );
            }

            return $this->handleResponseWithDataType(
                '\Toppy\Sendcloud\Model\ShippingProduct[]',
                $request,
                $response,
            );
        } catch (ApiException $apiException) {
            switch ($apiException->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        '\Toppy\Sendcloud\Model\ShippingProduct[]',
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);
                    throw $apiException;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        \Toppy\Sendcloud\Model\ScPublicV2AddressesGetSenderAddressById404Response::class,
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);
                    throw $apiException;
            }
        

            throw $apiException;
        }
    }

    /**
     * Operation scPublicV2ScpGetRetrieveAllShippingProductsAsync
     *
     * Retrieve a list of shipping products
     *
     * @param  string $fromCountry A country ISO 2 code for a from country (origin country). (required)
     * @param  \Toppy\Sendcloud\Model\CountryCodes $toCountry A country ISO 2 code for the recipient country. Required if the carrier is zonal or &#x60;contract_pricing&#x60; parameter is provided. (optional)
     * @param  string $carrier A carrier code. (optional)
     * @param  int $contract The contract id used for shipping product/method filtering. It has a similar effect as using the &#x60;carrier&#x60; parameter. If the &#x60;contract_pricing&#x60; parameter is used, the carrier is used to provide the correct contract pricing. Only required if multiple contract prices exist for the same shipping method. (optional)
     * @param  int $weight The weight of the shipment. (optional)
     * @param  string $weightUnit The unit for the shipment weight. Required if the &#x60;weight&#x60; parameter is provided. (optional)
     * @param  int $length The length of the shipment. Required if the &#x60;width&#x60; and/or &#x60;height&#x60; parameters are provided. (optional)
     * @param  string $lengthUnit The unit for the shipment length. Required if the &#x60;length&#x60; parameter is provided. (optional)
     * @param  int $width The width of the shipment. Required if the &#x60;length&#x60; and/or &#x60;height&#x60; parameters are provided. (optional)
     * @param  string $widthUnit The unit for the shipment width. Required if the “width” parameter is provided. (optional)
     * @param  int $height The height of the shipment. Required if the “width” and/or “length” parameters are provided. (optional)
     * @param  string $heightUnit The unit for the shipment height. Required if the “height” parameter is provided. (optional)
     * @param  int $leadTimeHours Filters shipping products (rather its associated shipping methods) by their transit time. This is the estimated time a shipment takes between a parcel is being picked up by a carrier and it reaching its destination. This parameter supports comparison operators (e.g. &#x60;lead_time_hours[gte]&#x3D;12&#x60; for filtering out shipments that have less than 12 hours transit time or &#x60;lead_time_hours[gte&#x3D;24]&amp;lead_time_hours[lte]&#x3D;48&#x60; for only including shipping products whose methods have a transit time between 24 and 48 hours). Available operators are “eq” (equal), “gt” (greater than), “lt” (less than), “gte” (greater than or equal), and “lte” (less than or equal). (optional)
     * @param  bool $contractPricing Whether to include contract prices in the response. This parameter is only available to users upon request. Please contact customer support. (optional)
     * @param  string $fromPostalCode Postal code of the sender. Required if the carrier is zonal. (optional)
     * @param  string $toPostalCode Postal code of the recipient. Required if the carrier is zonal. (optional)
     * @param  bool $returns If set to &#x60;true&#x60; the endpoint will return shipping methods which can be used for making a return  shipment. (optional, default to false)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV2ScpGetRetrieveAllShippingProductsAsync($fromCountry, $toCountry = null, $carrier = null, $contract = null, $weight = null, $weightUnit = null, $length = null, $lengthUnit = null, $width = null, $widthUnit = null, $height = null, $heightUnit = null, $leadTimeHours = null, $contractPricing = null, $fromPostalCode = null, $toPostalCode = null, $returns = false)
    {
        return $this->scPublicV2ScpGetRetrieveAllShippingProductsAsyncWithHttpInfo($fromCountry, $toCountry, $carrier, $contract, $weight, $weightUnit, $length, $lengthUnit, $width, $widthUnit, $height, $heightUnit, $leadTimeHours, $contractPricing, $fromPostalCode, $toPostalCode, $returns)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation scPublicV2ScpGetRetrieveAllShippingProductsAsyncWithHttpInfo
     *
     * Retrieve a list of shipping products
     *
     * @param  string $fromCountry A country ISO 2 code for a from country (origin country). (required)
     * @param  \Toppy\Sendcloud\Model\CountryCodes $toCountry A country ISO 2 code for the recipient country. Required if the carrier is zonal or &#x60;contract_pricing&#x60; parameter is provided. (optional)
     * @param  string $carrier A carrier code. (optional)
     * @param  int $contract The contract id used for shipping product/method filtering. It has a similar effect as using the &#x60;carrier&#x60; parameter. If the &#x60;contract_pricing&#x60; parameter is used, the carrier is used to provide the correct contract pricing. Only required if multiple contract prices exist for the same shipping method. (optional)
     * @param  int $weight The weight of the shipment. (optional)
     * @param  string $weightUnit The unit for the shipment weight. Required if the &#x60;weight&#x60; parameter is provided. (optional)
     * @param  int $length The length of the shipment. Required if the &#x60;width&#x60; and/or &#x60;height&#x60; parameters are provided. (optional)
     * @param  string $lengthUnit The unit for the shipment length. Required if the &#x60;length&#x60; parameter is provided. (optional)
     * @param  int $width The width of the shipment. Required if the &#x60;length&#x60; and/or &#x60;height&#x60; parameters are provided. (optional)
     * @param  string $widthUnit The unit for the shipment width. Required if the “width” parameter is provided. (optional)
     * @param  int $height The height of the shipment. Required if the “width” and/or “length” parameters are provided. (optional)
     * @param  string $heightUnit The unit for the shipment height. Required if the “height” parameter is provided. (optional)
     * @param  int $leadTimeHours Filters shipping products (rather its associated shipping methods) by their transit time. This is the estimated time a shipment takes between a parcel is being picked up by a carrier and it reaching its destination. This parameter supports comparison operators (e.g. &#x60;lead_time_hours[gte]&#x3D;12&#x60; for filtering out shipments that have less than 12 hours transit time or &#x60;lead_time_hours[gte&#x3D;24]&amp;lead_time_hours[lte]&#x3D;48&#x60; for only including shipping products whose methods have a transit time between 24 and 48 hours). Available operators are “eq” (equal), “gt” (greater than), “lt” (less than), “gte” (greater than or equal), and “lte” (less than or equal). (optional)
     * @param  bool $contractPricing Whether to include contract prices in the response. This parameter is only available to users upon request. Please contact customer support. (optional)
     * @param  string $fromPostalCode Postal code of the sender. Required if the carrier is zonal. (optional)
     * @param  string $toPostalCode Postal code of the recipient. Required if the carrier is zonal. (optional)
     * @param  bool $returns If set to &#x60;true&#x60; the endpoint will return shipping methods which can be used for making a return  shipment. (optional, default to false)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV2ScpGetRetrieveAllShippingProductsAsyncWithHttpInfo($fromCountry, $toCountry = null, $carrier = null, $contract = null, $weight = null, $weightUnit = null, $length = null, $lengthUnit = null, $width = null, $widthUnit = null, $height = null, $heightUnit = null, $leadTimeHours = null, $contractPricing = null, $fromPostalCode = null, $toPostalCode = null, $returns = false)
    {
        $returnType = '\Toppy\Sendcloud\Model\ShippingProduct[]';
        $request = $this->scPublicV2ScpGetRetrieveAllShippingProductsRequest($fromCountry, $toCountry, $carrier, $contract, $weight, $weightUnit, $length, $lengthUnit, $width, $widthUnit, $height, $heightUnit, $leadTimeHours, $contractPricing, $fromPostalCode, $toPostalCode, $returns);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $httpException) {
                    $response = $httpException->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $httpException->getRequest()->getUri()
                        ),
                        $httpException->getRequest(),
                        $httpException->getResponse(),
                        $httpException
                    );
                }
            );
    }

    /**
     * Create request for operation 'scPublicV2ScpGetRetrieveAllShippingProducts'
     *
     * @param  string $fromCountry A country ISO 2 code for a from country (origin country). (required)
     * @param  \Toppy\Sendcloud\Model\CountryCodes $toCountry A country ISO 2 code for the recipient country. Required if the carrier is zonal or &#x60;contract_pricing&#x60; parameter is provided. (optional)
     * @param  string $carrier A carrier code. (optional)
     * @param  int $contract The contract id used for shipping product/method filtering. It has a similar effect as using the &#x60;carrier&#x60; parameter. If the &#x60;contract_pricing&#x60; parameter is used, the carrier is used to provide the correct contract pricing. Only required if multiple contract prices exist for the same shipping method. (optional)
     * @param  int $weight The weight of the shipment. (optional)
     * @param  string $weightUnit The unit for the shipment weight. Required if the &#x60;weight&#x60; parameter is provided. (optional)
     * @param  int $length The length of the shipment. Required if the &#x60;width&#x60; and/or &#x60;height&#x60; parameters are provided. (optional)
     * @param  string $lengthUnit The unit for the shipment length. Required if the &#x60;length&#x60; parameter is provided. (optional)
     * @param  int $width The width of the shipment. Required if the &#x60;length&#x60; and/or &#x60;height&#x60; parameters are provided. (optional)
     * @param  string $widthUnit The unit for the shipment width. Required if the “width” parameter is provided. (optional)
     * @param  int $height The height of the shipment. Required if the “width” and/or “length” parameters are provided. (optional)
     * @param  string $heightUnit The unit for the shipment height. Required if the “height” parameter is provided. (optional)
     * @param  int $leadTimeHours Filters shipping products (rather its associated shipping methods) by their transit time. This is the estimated time a shipment takes between a parcel is being picked up by a carrier and it reaching its destination. This parameter supports comparison operators (e.g. &#x60;lead_time_hours[gte]&#x3D;12&#x60; for filtering out shipments that have less than 12 hours transit time or &#x60;lead_time_hours[gte&#x3D;24]&amp;lead_time_hours[lte]&#x3D;48&#x60; for only including shipping products whose methods have a transit time between 24 and 48 hours). Available operators are “eq” (equal), “gt” (greater than), “lt” (less than), “gte” (greater than or equal), and “lte” (less than or equal). (optional)
     * @param  bool $contractPricing Whether to include contract prices in the response. This parameter is only available to users upon request. Please contact customer support. (optional)
     * @param  string $fromPostalCode Postal code of the sender. Required if the carrier is zonal. (optional)
     * @param  string $toPostalCode Postal code of the recipient. Required if the carrier is zonal. (optional)
     * @param  bool $returns If set to &#x60;true&#x60; the endpoint will return shipping methods which can be used for making a return  shipment. (optional, default to false)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function scPublicV2ScpGetRetrieveAllShippingProductsRequest($fromCountry, $toCountry = null, $carrier = null, $contract = null, $weight = null, $weightUnit = null, $length = null, $lengthUnit = null, $width = null, $widthUnit = null, $height = null, $heightUnit = null, $leadTimeHours = null, $contractPricing = null, $fromPostalCode = null, $toPostalCode = null, $returns = false)
    {
        // verify the required parameter 'fromCountry' is set
        if ($fromCountry === null || (is_array($fromCountry) && $fromCountry === [])) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $fromCountry when calling scPublicV2ScpGetRetrieveAllShippingProducts'
            );
        }

        if ($weight !== null && $weight < 0) {
            throw new \InvalidArgumentException('invalid value for "$weight" when calling ShippingProductsApi.scPublicV2ScpGetRetrieveAllShippingProducts, must be bigger than or equal to 0.');
        }

        if ($length !== null && $length < 0) {
            throw new \InvalidArgumentException('invalid value for "$length" when calling ShippingProductsApi.scPublicV2ScpGetRetrieveAllShippingProducts, must be bigger than or equal to 0.');
        }

        if ($width !== null && $width < 0) {
            throw new \InvalidArgumentException('invalid value for "$width" when calling ShippingProductsApi.scPublicV2ScpGetRetrieveAllShippingProducts, must be bigger than or equal to 0.');
        }

        if ($height !== null && $height < 0) {
            throw new \InvalidArgumentException('invalid value for "$height" when calling ShippingProductsApi.scPublicV2ScpGetRetrieveAllShippingProducts, must be bigger than or equal to 0.');
        }

        if ($fromPostalCode !== null && strlen($fromPostalCode) > 12) {
            throw new \InvalidArgumentException('invalid length for "$fromPostalCode" when calling ShippingProductsApi.scPublicV2ScpGetRetrieveAllShippingProducts, must be smaller than or equal to 12.');
        }

        if ($toPostalCode !== null && strlen($toPostalCode) > 12) {
            throw new \InvalidArgumentException('invalid length for "$toPostalCode" when calling ShippingProductsApi.scPublicV2ScpGetRetrieveAllShippingProducts, must be smaller than or equal to 12.');
        }


        $resourcePath = '/shipping-products';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;
        // query params
        if(is_array($fromCountry)) {
            foreach($fromCountry as $key => $value) {
                $queryParams[$key] = $value;
            }
        }
        else {
            $queryParams['from_country'] = $fromCountry;
        }

        // query params
        if ($toCountry !== null) {
            if(is_array($toCountry)) {
                foreach($toCountry as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['to_country'] = $toCountry;
            }
        }

        // query params
        if ($carrier !== null) {
            if(is_array($carrier)) {
                foreach($carrier as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['carrier'] = $carrier;
            }
        }

        // query params
        if ($contract !== null) {
            if(is_array($contract)) {
                foreach($contract as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['contract'] = $contract;
            }
        }

        // query params
        if ($weight !== null) {
            if(is_array($weight)) {
                foreach($weight as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['weight'] = $weight;
            }
        }

        // query params
        if ($weightUnit !== null) {
            if(is_array($weightUnit)) {
                foreach($weightUnit as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['weight_unit'] = $weightUnit;
            }
        }

        // query params
        if ($length !== null) {
            if(is_array($length)) {
                foreach($length as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['length'] = $length;
            }
        }

        // query params
        if ($lengthUnit !== null) {
            if(is_array($lengthUnit)) {
                foreach($lengthUnit as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['length_unit'] = $lengthUnit;
            }
        }

        // query params
        if ($width !== null) {
            if(is_array($width)) {
                foreach($width as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['width'] = $width;
            }
        }

        // query params
        if ($widthUnit !== null) {
            if(is_array($widthUnit)) {
                foreach($widthUnit as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['width_unit'] = $widthUnit;
            }
        }

        // query params
        if ($height !== null) {
            if(is_array($height)) {
                foreach($height as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['height'] = $height;
            }
        }

        // query params
        if ($heightUnit !== null) {
            if(is_array($heightUnit)) {
                foreach($heightUnit as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['height_unit'] = $heightUnit;
            }
        }

        // query params
        if ($leadTimeHours !== null) {
            if(is_array($leadTimeHours)) {
                foreach($leadTimeHours as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['lead_time_hours'] = $leadTimeHours;
            }
        }

        // query params
        if ($contractPricing !== null) {
            if(is_array($contractPricing)) {
                foreach($contractPricing as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['contract_pricing'] = $contractPricing;
            }
        }

        // query params
        if ($fromPostalCode !== null) {
            if(is_array($fromPostalCode)) {
                foreach($fromPostalCode as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['from_postal_code'] = $fromPostalCode;
            }
        }

        // query params
        if ($toPostalCode !== null) {
            if(is_array($toPostalCode)) {
                foreach($toPostalCode as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['to_postal_code'] = $toPostalCode;
            }
        }

        // query params
        if ($returns !== null) {
            if(is_array($returns)) {
                foreach($returns as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['returns'] = $returns;
            }
        }




        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }


    /**
     * @param string|UriInterface $uri
     * @param string[] $headers
     * @param string|StreamInterface|null $body
     *
     */
    protected function createRequest(string $method, $uri, array $headers = [], $body = null): RequestInterface
    {
        if ($this->requestFactory instanceof RequestFactory) {
            return $this->requestFactory->createRequest(
                $method,
                $uri,
                $headers,
                $body
            );
        }

        if (is_string($body) && '' !== $body && null === $this->streamFactory) {
            throw new \RuntimeException('Cannot create request: A stream factory is required to create a request with a non-empty string body.');
        }

        $request = $this->requestFactory->createRequest($method, $uri);

        foreach ($headers as $key => $value) {
            $request = $request->withHeader($key, $value);
        }

        if (null !== $body && '' !== $body) {
            return $request->withBody(
                is_string($body) ? $this->streamFactory->createStream($body) : $body
            );
        }

        return $request;
    }

    /**
     * @param array<array<string, mixed>, mixed> $queryParams
     */
    private function createUri(
        string $operationHost,
        string $resourcePath,
        array $queryParams
    ): UriInterface {
        $parsedUrl = parse_url($operationHost);

        $host = $parsedUrl['host'] ?? null;
        $scheme = $parsedUrl['scheme'] ?? null;
        $basePath = $parsedUrl['path'] ?? null;
        $port = $parsedUrl['port'] ?? null;
        $user = $parsedUrl['user'] ?? null;
        $password = $parsedUrl['pass'] ?? null;

        $uri = $this->uriFactory->createUri($basePath . $resourcePath)
            ->withHost($host)
            ->withScheme($scheme)
            ->withPort($port)
            ->withQuery(ObjectSerializer::buildQuery($queryParams));

        if ($user) {
            return $uri->withUserInfo($user, $password);
        }

        return $uri;
    }

    /**
     * @return array<int, object|int|mixed[]|null>
     */
    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
			$request,
                        $response,
                        $exception
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }
}
