<?php
/**
 * LabelSingleResponseTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Toppy\Sendcloud\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sendcloud Public REST API
 *
 * Complete Sendcloud API v2 specification - merged from official sendcloud.dev documentation
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: contact@sendcloud.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Toppy\Sendcloud\V2\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * LabelSingleResponseTest Class Doc Comment
 *
 * @category    Class
 * @description LabelSingleResponse
 * @package     Toppy\Sendcloud\V2
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class LabelSingleResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "LabelSingleResponse"
     */
    public function testLabelSingleResponse()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "label"
     */
    public function testPropertyLabel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "customsDeclaration"
     */
    public function testPropertyCustomsDeclaration()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
